### ISSUE TITLE
Undefined exception

### ISSUE THREAD

**Issue by barbatus** [Urigo/angular-meteor#246] opened 2015-03-20 15:44 UTC
I think [here](https://github.com/Urigo/angular-meteor/blob/master/modules/angular-meteor-meteorCollection.js#L207) this.observeHandle needs to be checked if it's defined already.
I get undefined exceptions sometimes.

**Comment by Urigo** [comment] 2015-03-20 17:55
Interesting, can you show me a reproduction?
Also, it look simple to solve, would you want to pull request it to get the credit?

**Comment by barbatus** [comment] 2015-03-20 21:25
Pls check console
http://ng-meteor.meteor.com/
Repo https://github.com/barbatus/ng-meteor

I think the bottleneck here (and partly the reason) is that $rootScope.$apply() runs every time new element added to the collection initially. It's not optimal by itself. More appropriate strategy would be 1) apply scope after **all** initial elements added to the collection 2) apply every next single element changed or added.

In the deployed example above,
right after *reactiveFunc* has been executed reactively **second time** [here](https://github.com/Urigo/angular-meteor/blob/master/modules/angular-meteor-meteorCollection.js#L290) (i.e. it has _limit_ dependency defined already) for the collection foo2 , at the exact moment new element may have been inserted into the collection foo1 which applies  scope and causes all [$watch] (https://github.com/Urigo/angular-meteor/blob/master/modules/angular-meteor-reactive-scope.js#L21)s to run and invalidate current computations (via *dependency.changed*). Then [Tracker.onInvalidate](https://github.com/Urigo/angular-meteor/blob/master/modules/angular-meteor-meteorCollection.js#L287) is being executed but foo2 still doesn't have an observer to stop.

**Comment by Urigo** [comment] 2015-03-22 10:49
About your first point - when we worked on the last performance boost we did exactly that at the beginning but then ended up improving that so much we didn't needed that, but it still might make since - @netanelgilad thinking about re-adding that?

@barbatus do you think that plus checking if
 
    this.observeHandle.stop();

exists before executing that is enough?

If so, can you add a pull request for that simple check? I want to release a new version today or tomorrow and want to include that.

**Comment by Urigo** [comment] 2015-03-22 10:54
by the way, very nice reproduction!

**Comment by barbatus** [comment] 2015-03-22 15:37
It's ok if it's 10 elements in a collection but if it's 100 elements it might be freezing to apply scope 100 times.
I would suggest another one method - _start_ (good symmetrical addition to the _stop_) and a boolean option to the constructor which indicates observing state at the construction.
Thus, an optimized way to follow may be:
````js
$scope.foo = $meteorCollection(function() {
   return Foo.find();
}, true, false /*don't observe*/);
$subscribe('foo').then(function() {
   // Start observing when subscription is ready
   $scope.foo.start();
})
`````

BTW, this [commit](https://github.com/Urigo/angular-meteor/commit/56ca4a5821576a6bdd626356f9f0c811e8c16972) seems didn't get to the last releast, do you plan to add it to next one?

**Comment by stlouisweb** [comment] 2015-03-22 16:18
Perhaps a meteor.defer() could be injected in the $rootScope.$apply() loop to make the function non-blocking. I haven't looked at the code, but meteor defer would essentially pop of the callstack each new $rootScope.$apply() for each doc in the collection, freeing up the app to do other things while applying scope.

**Comment by Urigo** [comment] 2015-03-22 17:29
@barbatus that's interesting but I'm not sure there is a problem...  have you actually encountered a freezing problem?
if you will look at the $watch function you can see we make it very optimized and we tested it with a lot of items.
If it's ok I would rather not add it to the API, but if it does I might reconsider.
About your commit, I'm not sure....  do you want to reopen that pull request?

@stlouisweb I'm not sure I understand..  maybe can you show an example in a branch, even a non working one

**Comment by barbatus** [comment] 2015-03-22 18:07
@Urigo BTW, that $watch looks strange to me, why it's not?:
````js
     self.$watch(function() {
        return getValue(self)
      }, function(newVal, oldVal) {
        if (newVal != oldVal) {
            self.$$trackerDeps[property].changed();
        }
      });
````

**Comment by barbatus** [comment] 2015-03-22 18:16
@Urigo Just checked once more, my bad, that pull request was added right after previous release, so should be a new one

**Comment by Urigo** [comment] 2015-03-22 19:44
I'm not sure I understand your two last comments, sorry :)

**Comment by barbatus** [comment] 2015-03-22 20:05
1) I mean this [$watch](https://github.com/Urigo/angular-meteor/blob/master/modules/angular-meteor-reactive-scope.js#L21). It's executed every $apply, hence, it needs ```` if (newVal != oldVal)````

2) I was wrong about the commit, never mind. (that [PR](https://github.com/Urigo/angular-meteor/pull/220) will be in next release).

**Comment by netanelgilad** [comment] 2015-03-22 20:29
@barbatus about 1.
The check is actually needed but it should not affect performance since newVal === oldVal only happens once in the watcher initialization as described in the angular docs https://docs.angularjs.org/api/ng/type/$rootScope.Scope#$watch.

**Comment by Urigo** [comment] 2015-03-22 20:32
@netanelgilad can you add that now before I release a new version?

**Comment by netanelgilad** [comment] 2015-03-22 20:38
@Urigo any way, we need to return the apply optimization we had when working on performance..

**Comment by barbatus** [comment] 2015-03-22 20:59
@netanelgilad yes, you're right

**Comment by Urigo** [comment] 2015-03-22 22:14
@netanelgilad yes, also the move to a separate service, it's still in a branch

**Comment by Urigo** [comment] 2015-03-22 22:17
but just remember that it really wasn't that segnificant compared to the watch twicks...

**Comment by Urigo** [comment] 2015-03-22 22:19
OK looks like the original problem in this thread has solved.
Closing that now.
@netanelgilad we will work on that performance improvement but @barbatus , I would love a reproduction for a scenario where it makes real difference, so we can compare our code to

**Closed by Urigo** 2015-03-22 22:19 UTC

**Comment by barbatus** [comment] 2015-03-22 22:27
@Urigo I don't have any freezing issue or anything close (but I haven't had enough docs in a collection to give it a chance). Main point here is that adding docs one by one to the DOM is essentially slower than adding all of them at once.
Ok about closing this; everything else is up to you.

**Comment by barbatus** [comment] 2015-03-23 18:04
@Urigo I just gave it a whirl with 100 documents on a page. So it takes ~2sec to render without $apply  and 1min!! with. It definitely needs perf optimization.

**Comment by Urigo** [comment] 2015-03-29 13:52
@barbatus care to try a pull request?

**Comment by barbatus** [comment] 2015-03-31 22:20
@Urigo Hm, what kind of PR? For reproduce?

**Comment by Urigo** [comment] 2015-04-01 19:50
PR for the initial load (would be great with a reproduction as well)

**Comment by barbatus** [comment] 2015-04-11 10:57
@Urigo 
Sorry for the delay, it took some time to investigate.
I seem to have found main reason why it was so time consuming to render e.g. 100 documents on a page in my case. It’s mainly because of ‘heavy’ templates with a bunch of helper functions that were executed every time a scope was applied. So when I added one-time bindings instead, i.e. with '::' like ````{{::foo}}````, speed improved multiple times. Then I added the following tweak:
````js
addedAt: function (document, atIndex) {
      self.splice(atIndex, 0, document);

      if (handler) {
        clearTimeout(handler);
      }

      handler = setTimeout(function() {
        $rootScope.$apply();
      }, 15);
    }
````
and speed improved again. Not much as before but yet considerably.
I think it makes sense to add something like above given Angular is inherently slower than a ‘native’ realization would be (as my issue showed).
Also one question regarding rationale behind this [line](https://github.com/Urigo/angular-meteor/blob/master/modules/angular-meteor-meteorCollection.js#L208): why not just this.length = 0?

Alex

**Comment by netanelgilad** [comment] 2015-04-11 11:42
@barbatus that's the reason for the pop: https://jsperf.com/array-destroy/40
maybe we need to add a comment above it.
And about the timeout, that is a really needed change. Even angular $http has this kind of thing called $useApplyAsync. Collectiona few add events into a single appy is something we should add.
Using the timeout is a good option, but also need to check how angular implemented $useApplyAsync (probably the same way...).

**Comment by barbatus** [comment] 2015-04-11 13:22
@netanelgilad ha, I got version with the shift even faster; they seems to be approx. the same as well as ````arr=[]```` (which was actually my second 'why not' thought). So given it's much less code, I'd choose it (anyways it doesn't matter much).
About the timeout. Ok, I'll check $useApplyAsync and send PR.

**Comment by barbatus** [comment] 2015-04-11 13:30
@netanelgilad LOL, I just checked it on Chrome and it's different in comparison to Safari, now ````arr=[]```` is 75% slower. So never mind, JS is sometimes tough )

**Comment by barbatus** [comment] 2015-04-12 09:53
@netanelgilad check it out pls [ng-meteor.meteor.com](ng-meteor.meteor.com), I send out PR also.
It seems to work as expected; i tried also $asyncApply but it didn't work - it only works when it's applied after all elements have been added to the collection.
