### ISSUE TITLE
client/app.ts (3, 42): Cannot find module 'angular2/angular2'.

### ISSUE THREAD

**Issue by 7immy** [Urigo/angular-meteor#996] opened 2015-12-22 21:41 UTC
Trying to go through your angular2 tutorial and constantly keep hitting this road block.
 Does anyone know how I can resolve this?

Error:
client/app.ts (3, 42): Cannot find module 'angular2/angular2'.

The code in question:
````
/// <reference path="../typings/angular2-meteor.d.ts" />

import {Component, View, bootstrap} from 'angular2/angular2';

@Component({
    selector: 'app'
})
@View({
    templateUrl: 'client/app.html'
})
class Socially { }

bootstrap(Socially);
````

**Comment by jacobdr** [comment] 2015-12-22 23:04
Maybe the leading slash on typing is looking in your root directory. You may want to just try:




/// <reference path="typings/angular2-meteordts" /> i





Or some other variety of path modification



—

**Comment by Sauermann** [comment] 2015-12-27 02:00
The tutorial seems to be outdated. For me it worked after changing the import statement to:

    import {Component, View} from 'angular2/core';
    import {bootstrap} from 'angular2/bootstrap';

**Comment by Urigo** [comment] 2015-12-28 10:15
@barbatus should we update the tutorial?

**Comment by Sauermann** [comment] 2015-12-28 10:17
Looks like the tutorial has been updated already.

**Comment by barbatus** [comment] 2015-12-28 10:20
Hey guys, the tutorial has been updated for the Angular2 Beta right after its release, I don't know where you find issues like that?

**Comment by Urigo** [comment] 2015-12-28 12:27
ok closing

**Closed by Urigo** 2015-12-28 12:27 UTC

**Comment by scenaristeur** [comment] 2016-01-07 23:39
i though I had an error too, and landed to this page.
 Perharps you should mention near "0.5  Create root component"  something like 
"Here you got 'Error:
client/app.ts (3, 42): Cannot find module 'angular2/angular2'.' 
message in terminal, don't care we will fix it later"

**Comment by gentunian** [comment] 2016-02-15 17:30
Following the tutorial from: http://www.angular-meteor.com/tutorials/socially/angular2/bootstrapping I've got the same error with meteor `1.2.1` from scratch:

```
$ meteor create socially-ng2-ionic2
Created a new Meteor app in 'socially-ng2-ionic2'.

To run your new app:                          
  cd socially-ng2-ionic2                      
  meteor                                      
                                              
If you are new to Meteor, try some of the learning resources here:
  https://www.meteor.com/learn                
                                              
$ cd socially-ng2-ionic2/
$ meteor add urigo:angular2-meteor
                                              
Changes to your project's package version selections:
                                              
barbatus:angular2       added, version 0.8.5_2
barbatus:ng2-compilers  added, version 0.1.1
barbatus:ts-compilers   added, version 0.2.8_4
barbatus:typescript     added, version 0.1.5
systemjs:systemjs       added, version 0.18.4
urigo:angular2-meteor   added, version 0.4.2

                                              
urigo:angular2-meteor: Angular2 and Meteor integration
$ meteor remove blaze-html-templates
                                              
Changes to your project's package version selections:
                                              
blaze-html-templates   removed from your project
caching-html-compiler  removed from your project
templating             removed from your project
templating-tools       removed from your project

blaze-html-templates: removed dependency      
$ meteor remove ecmascript
ecmascript: removed dependency                
$ meteor add barbatus:ionic2-meteor
                                              
Changes to your project's package version selections:
                                              
barbatus:ionic2-meteor  added, version 0.1.6  

                                              
barbatus:ionic2-meteor: Ionic2 Npm packaged for Meteor
[seba@ccnotstreu socially-ng2-ionic2]$ meteor 
[[[[[ ~/meteor-projects/socially-ng2-ionic2 ]]]]]

=> Started proxy.                             
=> Started MongoDB.                           
client/app.ts (1, 31): Cannot find module 'angular2/core'.
client/app.ts (3, 25): Cannot find module 'angular2/platform/browser'.
client/app.ts (5, 25): Cannot find module 'ionic2-meteor'.
***** New typings have been added *****      /
typings/angular2/core.d.ts
typings/angular2/core_amb.d.ts
typings/angular2/common.d.ts
typings/angular2/common_amb.d.ts
typings/angular2/platform/browser.d.ts
typings/angular2/platform/browser_amb.d.ts
typings/angular2/router.d.ts
typings/angular2/router_amb.d.ts
typings/angular2/angular2.d.ts
typings/angular2-meteor/angular2-meteor.d.ts
typings/ionic2-meteor/ionic-framework/ionic.d.ts
typings/ionic2-meteor/ionic2-meteor.d.ts
Add typings in tsconfig.json or by references in files.
=> Errors prevented startup:                  
   
   While processing files with urigo:angular2-meteor (for target web.browser):
   <anonymous>: socially-ng2-ionic2.html has wrong layout
   at Error (<anonymous>)
   at compilers/html_compiler.js:26:15
   at Array.forEach (native)
   at HtmlCompiler.processFilesForTarget (compilers/html_compiler.js:18:11)
   
   
   While processing files with urigo:angular2-meteor (for target os.linux.x86_64):
   <anonymous>: socially-ng2-ionic2.html has wrong layout
   at Error (<anonymous>)
   at compilers/html_compiler.js:26:15
   at Array.forEach (native)
   at HtmlCompiler.processFilesForTarget (compilers/html_compiler.js:18:11)
```

I first created this `app.ts`

```
import {Component, View} from 'angular2/core';
import {MeteorApp} from 'ionic2-meteor';
import {bootstrap} from 'angular2/platform/browser';


@Component({
    selector: 'app'
    })
@View({
    template: 'Hello World!'
    })

class Socially {}

bootstrap(Socially);
```

Finally I left the file like this: 

```
import {Component, View} from 'angular2/core';

import {bootstrap} from 'angular2/platform/browser';


@Component({
    selector: 'app'
    })
@View({
    template: 'Hello World!'
    })

class Socially {}

bootstrap(Socially);
```

**Comment by barbatus** [comment] 2016-02-15 17:57
@gentunian your socially-ng2-ionic2.html has wrong layout for the package, i.e., it contains `Template` tag. This actually is noted in the tutorial, i don't know how clear it's stated but most seems be able to grasp it properly. Second, it's better to place html files in `client` folder, boilerplate app has it in the root.

**Comment by gentunian** [comment] 2016-02-15 21:06
@barbatus you were right about templating, my idea was to show the error related to the issue. I removed all previously generated files and I left only the `app.ts` and the `index.html` for paste the error:

```
$ meteor 
[[[[[ ~/meteor-projects/socially-ng2-ionic2 ]]]]]

=> Started proxy.                             
=> Started MongoDB.                           
client/app.ts (1, 31): Cannot find module 'angular2/core'.
client/app.ts (3, 25): Cannot find module 'angular2/platform/browser'.
=> Started your app.                          

=> App running at: http://localhost:3000/
```
Despite that getting the error complaining about modules, "Hello World!" is printed.

**Comment by barbatus** [comment] 2016-02-16 16:02
Hey read carefully first step to the end, everything is explained there.

**Comment by gentunian** [comment] 2016-02-16 17:24
ooops! such a shame I made noise on this. Sry

**Comment by gentunian** [comment] 2016-02-16 19:45
Ok, I've just found that using

```
/// <reference path="typings/angular2-meteor/angular2-meteor.d.ts" />
```

inside `client/app.ts` won't work, because is referring to `typings` inside `client` directory:

```
client/app.ts (2, 31): Cannot find module 'angular2/core'.
client/app.ts (3, 25): Cannot find module 'angular2/platform/browser'.
client/app.ts (1, 1): File 'client/typings/angular2-meteor/angular2-meteor.d.ts' not found.
```

This is working ok:

```
/// <reference path="../typings/angular2-meteor/angular2-meteor.d.ts" />
```

Thanks,

**Comment by dvdgarcia** [comment] 2016-06-08 19:41
Hi! 

I did this tutorial a few times ago and everything ok, today I started and it seems there is an issue with angular2-meteor-polyfills depenency, I follow steps but this modulo doesn't load properly, I tried to add it manually with npm and it started to work but with some error in console:

Failed to parse SourceMap: http://localhost:3000/packages/547fdeddd5a1d8584f76b2afdac14ed10d216a74.map

I hope this is useful, you are doing a great job ;)

thanks

**Comment by mschlosser22** [comment] 2016-06-11 00:04
Hi, FYI angular2-meteor-polyfills dependency is also not loading for me either while walking through the tutorial.

**Comment by pablomoran** [comment] 2016-06-11 11:27
Getting the same issue using polyfills

**Comment by berndverhofstadt** [comment] 2016-06-12 13:12
I've found in [the documentation](https://github.com/Urigo/angular2-meteor#install-package) a way to run the app when getting the error `install.js:78 - Uncaught Error: Cannot find module 'angular2-meteor-polyfills/browser'`

* Install the dependency by running `meteor npm install --save angular2-meteor-polyfills`
* Add `import 'angular2-meteor-polyfills'` to `app.ts` file

Try again to run the app. 
I think they didn't include `'angular2-meteor-polyfills'` module in the `barbatus:angular2-runtime` package, but I'm not sure...

**Comment by nebiljabari** [comment] 2016-06-13 16:50
same has @dvdgarcia (without error ...yet). Thx @berndverhofstadt
@Urigo Maybe a note on the bootstrap tutorial page until better days ?

**Comment by showplans** [comment] 2016-06-14 12:48
I also had to run "meteor npm install --save angular2-meteor-polyfills", without needing the import statement.

**Comment by yaiceltg** [comment] 2016-06-14 14:39
+1

**Comment by khiewshikai** [comment] 2016-06-15 16:23
Also had to run "meteor npm install --save angular2-meteor-polyfills", thanks @berndverhofstadt !

**Comment by Urigo** [comment] 2016-06-17 15:03
@berndverhofstadt @nebiljabari @showplans @yaiceltg @khiewshikai or anyone else care to submit a [PR the first bootstrapping chapter](https://github.com/Urigo/angular-meteor-docs/edit/master/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_00.md) to update with new instructions?

**Comment by fidelis** [comment] 2016-07-20 21:44
Ok, I've read carefully all the steps in this issue, but I cant solve the problem. Can someone help me? I'm trying to study this tutorial http://www.angular-meteor.com/tutorials/socially/angular2/bootstrapping using Cloud9, even following all the instructions I still not able to see the "Hello World" in my browser:
I got those messages:
In console of Cloud9
```
[[[[[ ~/workspace ]]]]]                       

=> Started proxy.                             
=> Started MongoDB.                           
client/app.ts (2, 33): Cannot find module '@angular/core'.
client/app.ts (3, 27): Cannot find module '@angular/platform-browser-dynamic'.
client/app.ts (5, 22): Cannot find module './app.html'.
                                              
Unable to resolve some modules:

  "reflect-metadata" in /home/ubuntu/workspace/client/app.ts (web.browser)
  "@angular/core" in /home/ubuntu/workspace/client/app.ts (web.browser)
  "@angular/platform-browser-dynamic" in /home/ubuntu/workspace/client/app.ts (web.browser)
                                              
If you notice problems related to these missing modules, consider running:
                                              
  meteor npm install --save reflect-metadata @angular
                                              
=> Started your app.                          

=> App running at: http://0.0.0.0:8080/
```

And in the inspection of the browser:

`modules-runtime.js:439 Uncaught Error: Cannot find module 'angular2-meteor-polyfills/browser'
modules-runtime.js:439 Uncaught Error: Cannot find module 'reflect-metadata'`

**Comment by nebiljabari** [comment] 2016-07-20 22:18
Can you show us your `package.json` file ? 
Your `node_modules` folder have the corrolated dependencies ?

Question: by default Meteor run on port 3000 unless we specified one. Is it you who decided to run on 8080 ?

**Comment by fidelis** [comment] 2016-07-21 14:52
meteor --port $IP:$PORT ==> https://socially-fidelis-1.c9users.io (works fine)

pakage.json
`{
  "name": "socially",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "meteor-node-stubs": "~0.2.0"
  }
}
`
tsconfig.json 
`{
  "compilerOptions": {
    "experimentalDecorators": true,
    "module": "commonjs",
    "target": "es5",
    "isolatedModules": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "removeComments": false,
    "noImplicitAny": false,
    "sourceMap": true
  },
  "filesGlob": [
    "client/**/*.ts",
    "server/**/*.ts",
    "typings/**/*.d.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}`

typings.json
`{
  "name": "socially",
  "dependencies": {
    "es6-promise": "registry:npm/es6-promise#3.0.0+20160211003958"
  },
  "globalDependencies": {
    "es6-shim": "registry:dt/es6-shim#0.31.2+20160602141504",
    "meteor": "registry:env/meteor#1.3.0+20160713172414"
  }
}
`

**Comment by nebiljabari** [comment] 2016-07-21 15:10
I think it was what I suspected. You don't have the `@angular2` dependenties in your `package.json` 
I suggest you to run (or re-run) : `meteor npm install --save` like indicated in the bootstrap

```
$ meteor remove blaze-html-templates
$ meteor add angular2-compilers barbatus:angular2-runtime

$ meteor npm install --save meteor-node-stubs reflect-metadata angular2-meteor angular2-meteor-polyfills@^0.1.1 rxjs@5.0.0-beta.6 zone.js@^0.6.6 @angular/core@^2.0.0-rc.4 @angular/common@^2.0.0-rc.4 @angular/compiler@^2.0.0-rc.4 @angular/platform-browser@^2.0.0-rc.4 @angular/platform-browser-dynamic
```

And your `tsconfig.json` the `"filesGlob"` array should look like this :
```
"filesGlob": [
    "client/**/*.ts",
    "server/**/*.ts",
    "typings/**/*.d.ts"
  ],
```

**Comment by fidelis** [comment] 2016-07-21 18:21
Thats right I forgot to run this command: 

> meteor npm install --save meteor-node-stubs reflect-metadata angular2-meteor angular2-meteor-polyfills@^0.1.1 rxjs@5.0.0-beta.6 zone.js@^0.6.6 @angular/core@^2.0.0-rc.4 @angular/common@^2.0.0-rc.4 @angular/compiler@^2.0.0-rc.4 @angular/platform-browser@^2.0.0-rc.4 @angular/platform-browser-dynamic

**Comment by fidelis** [comment] 2016-07-21 18:21
It's working now, thanks very much!

**Comment by mariohmol** [comment] 2016-11-24 04:23
Having similar problem but with `@angular/core` , one question.. should use `angular2` or `@angular` ? very confused

**Comment by nebiljabari** [comment] 2016-11-24 23:38
@mariohmol You should run : `meteor npm i -S @angular/core` 
- @angular = official package | angular2 = unofficial package

I suggest you to use the boilerplate who holds all the standard packages needed to start
`meteor create --example angular2-boilerplate your-project-name` or run directly
`git clone https://github.com/bsliran/angular2-meteor-base your-project-name`

and then run `meteor npm i`

**Comment by mariohmol** [comment] 2016-11-25 01:02
Cool!!! Cause I made using the whatsapp clone.. its old style...  will start from the scratch then! Thanks!

**Comment by mariohmol** [comment] 2016-11-25 13:28
I just saw that this boilerplate is not using ionic2 .. and the way the whatsapp clone was designed i think is better as well , example `app\pages\chat` has css, js,html for each module 

This seem to be updated with angular2.1 specs

* https://www.angular-meteor.com/tutorials/whatsapp2/ionic/chats-page

**Comment by nebiljabari** [comment] 2016-11-25 16:38
@mariohmol sorry Mario I didn't know you was targeting specifically the What's App Clone Tutorial on my first comment.
Ok so let me be clear, this tutorial is wrote with Angular1 and more precisely Angular1.5(+) "**not**" Angular2. So indeed the boilerplate I suggest you will not match

_PS: I mean by (+) Angular1.5.1, Angular1.5.2 etc..._
