### ISSUE TITLE
Scope Issue

### ISSUE THREAD

**Issue by ndevr** [Urigo/angular-meteor#143] opened 2015-01-14 18:52 UTC
Hey, I'am not sure it is a scope issue but when I'am attaching a transform to a collection:

Parties = new Mongo.Collection("parties", {transform: function(doc) {
  console.log('transform called for: ', doc);
  return doc;
}});

then it's called exponential when I'am switching the views.

Example for meteor-angular-socially:

Attach a transform to the party collection and goto the overview http://localhost:3000/parties and create a new party. Goto the party details: http://localhost:3000/parties/yqRECuoBA8p22R2FH and check your console (you should see 2 transform calls). Now go back to the overview /parties. And again click on the detail of the last party and check the console (you should see 6 calls to the transform). I think that could be a memory leak but I'am not sure about this behavior.

**Comment by Urigo** [comment] 2015-01-21 06:08
@ndevr interesting, I haven't tried transform yet.

Can you create a repo for that so I can easily try it out and find the solution?

Thanks

**Comment by Urigo** [comment] 2015-01-30 01:27
@ndevr any news?

**Comment by ndevr** [comment] 2015-01-30 17:40
not yet... will do it this weekend

**Comment by Urigo** [comment] 2015-02-17 09:36
@ndevr does this pull request solve your problem?
https://github.com/Urigo/angular-meteor/pull/185#issuecomment-74574071

**Comment by Urigo** [comment] 2015-02-19 22:31
@ndevr just checked that finally myself and it works for me, without reproduction I'm closing this.

**Closed by Urigo** 2015-02-19 22:31 UTC
