### ISSUE TITLE
Got error running meteor build ./build/

### ISSUE THREAD

**Issue by vinhhungle** [Urigo/angular-meteor#1470] opened 2016-11-05 17:35 UTC
Hello,

I'm following meteor angular 2 tutorial, after install npm packages and start server successfully.
I've tried to build using command meteor build ./build/ but I got the below errors. 

```
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! angular2-meteor-base@ build: `meteor build ./build/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-meteor-base@ build script 'meteor build ./build/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-meteor-base package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     meteor build ./build/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-meteor-base
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-meteor-base
npm ERR! There is likely additional logging output above.
```

Also, when I try to run in production mode it also failed:

```
$ meteor run --production
Warning: The --production flag should only be used to simulate production bundling for testing
purposes. Use meteor build to create a bundle for production deployment. See:
https://guide.meteor.com/deployment.html
[[[[[ ~/meteor-ng2/starter ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While processing files with angular2-compilers (for target web.browser):
   /tools/isobuild/compiler-plugin.js:717:15: 'data' option to addAsset must be a Buffer or
   String.
   at ResourceSlot.addAsset (/tools/isobuild/compiler-plugin.js:717:15)
   at InputFile.addAsset (/tools/isobuild/compiler-plugin.js:482:24)
   at SassCompilerExtended.addCompileResult
   (packages/barbatus:css-compiler/compilers/basic_compiler.js:32:15)
   at packages/caching-compiler/multi-file-caching-compiler.js:144:14
   at packages/caching-compiler/multi-file-caching-compiler.js:97:11
   at
   /Users/hungle/.meteor/packages/angular2-compilers/.0.6.5.umg8wb++os+web.browser+web.cordova/plugin.Angular2Compilers.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:182:20
   at replenish
   (/Users/hungle/.meteor/packages/angular2-compilers/.0.6.5.umg8wb++os+web.browser+web.cordova/plugin.Angular2Compilers.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:317:21)
   at
   /Users/hungle/.meteor/packages/angular2-compilers/.0.6.5.umg8wb++os+web.browser+web.cordova/plugin.Angular2Compilers.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:328:15
   at Object.async.forEachLimit.async.eachLimit
   (/Users/hungle/.meteor/packages/angular2-compilers/.0.6.5.umg8wb++os+web.browser+web.cordova/plugin.Angular2Compilers.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:221:35)
   at SassCompilerExtended.processFilesForTarget
   (packages/caching-compiler/multi-file-caching-compiler.js:95:11)
   at _loop (packages/barbatus:css-compiler/compilers/style_compiler.js:20:26)
   at StyleCompiler.processFilesForTarget
   (packages/barbatus:css-compiler/compilers/style_compiler.js:18:36)
```

**Comment by dotansimha** [comment] 2016-11-06 10:55
Caused by https://github.com/Urigo/angular-meteor/issues/1466.

Closing the issue, please track it there, you can also find there workaround in the meantime.

**Closed by dotansimha** 2016-11-06 10:55 UTC
