### ISSUE TITLE
getting id of new object

### ISSUE THREAD

**Issue by Tallyb** [Urigo/angular-meteor#300] opened 2015-04-16 13:48 UTC
After pushing to a collection - how can I get the new oid generated for the object? 
Let's say in socially - I would like right after inserting the party, to go to its page? 

Could not find it in the issues / examples. 
Am I missing something?

**Comment by Urigo** [comment] 2015-04-16 22:54
If you want to use the promise returned from the saving, you can use .save(newItem)  method instead of the push and then you'll get a promise with the id.
Let me know if that worked for you

**Comment by Tallyb** [comment] 2015-04-17 17:53
Could not get that far, unfortunately. I am stuck on TypeError: The first argument of $collection must be a Meteor.Collection object.
I can share the code with you, if interested.

**Comment by Urigo** [comment] 2015-04-17 22:17
Yes please do

**Comment by auterium** [comment] 2015-04-18 17:22
@Tallyb I ran across that same error and the problem is tmeasday:publish-counts's version. The package stopped working properly on versions 0.3.5 & 0.3.6, but version 0.3.7 (latest) is properly working.

**Comment by Tallyb** [comment] 2015-04-19 03:42
Do I need to do anything explicit to update?

**Comment by auterium** [comment] 2015-04-19 03:44
Just execute:meteor update tmeasday:publish-counts

**Comment by Tallyb** [comment] 2015-04-19 07:56
@auterium - I do not have this package in my project. My angular meteor was updated to 0.8.4 and the error still occur.

**Comment by auterium** [comment] 2015-04-19 12:42
@Tallyb then you'll have to share your code to see where this is happening. I got said error thanks to that package (which is used by the tutorial) and thought you had the same one

**Comment by Urigo** [comment] 2015-05-01 09:30
Closing after looking at the code and seeing it's not an angular-meteor issue  (would still love to help though)

**Closed by Urigo** 2015-05-01 09:30 UTC
