### ISSUE TITLE
Cant build angular2-meteor app

### ISSUE THREAD

**Issue by xylys** [Urigo/angular-meteor#1468] opened 2016-11-03 13:19 UTC
When I try to build my angular2-meteor app I get the following error

While processing files with angular2-compilers (for target web.browser):
/tools/isobuild/compiler-plugin.js:717:15: 'data' option to addAsset must be a Buffer or String.
at ResourceSlot.addAsset (/tools/isobuild/compiler-plugin.js:717:15)
at InputFile.addAsset (/tools/isobuild/compiler-plugin.js:482:24)
at SassCompilerExtended.addCompileResult (packages/barbatus:css-compiler/compilers/basic_compiler.js:32:15)
at packages/caching-compiler/multi-file-caching-compiler.js:144:14
at packages/caching-compiler/multi-file-caching-compiler.js:97:11
at
/Users/lukas/.meteor/packages/angular2-compilers/.0.6.5.jhir8j++os+web.browser+web.cordova/plugin.Angular2Compilers.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:182:20
at replenish
(/Users/lukas/.meteor/packages/angular2-compilers/.0.6.5.jhir8j++os+web.browser+web.cordova/plugin.Angular2Compilers.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:317:21)
at
/Users/lukas/.meteor/packages/angular2-compilers/.0.6.5.jhir8j++os+web.browser+web.cordova/plugin.Angular2Compilers.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:328:15
at Object.async.forEachLimit.async.eachLimit
(/Users/lukas/.meteor/packages/angular2-compilers/.0.6.5.jhir8j++os+web.browser+web.cordova/plugin.Angular2Compilers.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:221:35)
at SassCompilerExtended.processFilesForTarget (packages/caching-compiler/multi-file-caching-compiler.js:95:11)
at _loop (packages/barbatus:css-compiler/compilers/style_compiler.js:20:26)
at StyleCompiler.processFilesForTarget (packages/barbatus:css-compiler/compilers/style_compiler.js:18:36

**Comment by dotansimha** [comment] 2016-11-03 14:32
It's a duplicate of  https://github.com/Urigo/angular2-meteor/issues/430 & https://github.com/Urigo/angular2-meteor/issues/427.

There is an open issue (https://github.com/Urigo/angular-meteor/issues/1466) that we will fix soon.

**Closed by dotansimha** 2016-11-03 14:32 UTC
