### ISSUE TITLE
v1.3+ on a standalone client

### ISSUE THREAD

**Issue by nadavl** [Urigo/angular-meteor#1007] opened 2015-12-25 18:25 UTC
I'm running a standalone angular app using meteor-client-side, and after upgrading to 1.3 / 1.3.1, angular cannot resolve the `<$reactive>` service:

 Unknown provider: $reactiveProvider <- $reactive

Is there any issue with running v1.3 as a standalone client and not inside a meteor project?

**Comment by nadavl** [comment] 2015-12-25 22:42
OK Seems that when installing v1.3 / 1.3.1 from bower, the dist/bundle doesn't contain a dependency for `angular-meteor.reactive` .

Seems that the bower package is broken.

**Comment by dotansimha** [comment] 2015-12-26 10:12
Hi @nadavl , this issue is a duplicate of #985. 
I think that @idanwe takes care of this issue.

**Closed by dotansimha** 2015-12-26 10:12 UTC

**Comment by nadavl** [comment] 2015-12-26 13:17
Got it, thanks!
