### ISSUE TITLE
Deprecated collection binding was much faster

### ISSUE THREAD

**Issue by Xample** [Urigo/angular-meteor#208] opened 2015-02-28 10:44 UTC
I recently replaced the deprecated collection binding:
```javascript
$collection(aCollection).bind($scope, 'bindingName');
```
with
```javascript
$scope.bindingName = $meteor.collection(aCollection);
```
Unfortunately the performances drastically dropped. Displaying a list of those documents, I can imagine AngularJS has to redraw all the list each time a new document is inserted into the collection during the initial loading. Probably the bind function was using the same object references in order to allow AngularJS to only redraw modified items ? This does not seems to be the case using the affectation.

**Comment by netanelgilad** [comment] 2015-02-28 13:05
@Xample Can you share your use case and how you noticed the performance drop? 
The new collection API still works with the collection reference so it should now redraw all the list when a new item is inserted.
But maybe we missed something..

**Comment by Xample** [comment] 2015-02-28 14:25
Basically it is working but it looks like all the process is done within the main thread and stuck the UI the time the whole collection is loaded. The more the collection loads, the slower this even becomes so slow that the page even becomes irresponsive and I need to close it. I can hardly profile the page… will dig this more later if I can.

The venue is an entry using twitter bootstrap. Works like a charm with the bind function, here is the code (nothing more simple)
```xml
<li ng-repeat="venue in venues" class="media" ng-class="isSelectedVenue(venue._id) ? 'active' : ''" ng-click="selectVenue(venue._id)">
                            <a class="media-left" href="">
                                <img ng-src="{{::images.venue(venue.photos[0],'64x64')}}">
                            </a>
                            <div class="media-body">
                                <h4 class="media-heading">{{venue.name}}</h4>
                                <p>{{venue.address}}</p>
                            </div>
                        </li>
```

**Comment by netanelgilad** [comment] 2015-02-28 15:03
How big is your collection? Does it stop responding when the collection first loads or after an insert/update/delete operation?

**Comment by Xample** [comment] 2015-02-28 16:27
- The collection is 204 items, max 1mb of data (I am loading it locally so it is not a matter of bandwidth.)
- First load but also after updating an item, deleting and inserting.
- Same problem on Safari, Chrome and Firefox
- After profiling, the root comes from the Tracker.flush function, then safeApply spending most of the time on equals and copy
![screen shot 2015-02-28 at 20 25 06](https://cloud.githubusercontent.com/assets/944605/6426874/08f934fa-bf88-11e4-809f-435836d0ace6.png)

Based on the timeout, perhaps this take 204 ticks (one per item) before the page to actually get reloaded ?

Here is the Chrome canary profile file http://wikisend.com/download/770096/CPU-20150228T200757.cpuprofile

**Comment by netanelgilad** [comment] 2015-02-28 16:50
A lot of time being spent in equals and copy means a long time is being spent inside the digest cycle traversing the object being watched, as far as I can tell.
The objects in your collection, do they have a lot of properties and sub properties? 
If you can share your code or any reproduction i'd love to take a look.

**Comment by Xample** [comment] 2015-02-28 17:00
A lot of properties yes, here below is one entry. For sharing the code I will message you
```json
{
   "_id":"29",
   "originalData":{
      "Id":"29",
      "cat_id":"0",
      "company_id":null,
      "name":"The Observatory",
      "headline":"Afterwork drinks with the best view of the Palm",
      "image":"",
      "lat":"25.0877",
      "long":"55.1462",
      "address":"Dubai Marriott Harbour Hotel & Suites, Al Sufouh Road, Dubai Internet City, Dubai, 128358, United Arab Emirates",
      "summary":"Enticing. Tempting. Engaging. A feast for the eyes, the warm woods, custom lighting and modern décor help create the perfect setting for a dinner party with friends or business partners. With imposing views across Dubai, The Observatory is an audacious host. \n\nUnforgettable in its style and undeniable in its energy, The Observatory’s dynamic libations and cosmopolitan ambiance are as welcomed as the modish, melodious setting. As Dubai Marriott Harbour’s definitive destination venue, The Observatory serves up more than signature dishes and cocktails; it’s the ultimate night out.\n\n\n\n\n",
      "status":"1",
      "order":"29",
      "dt1":null,
      "dt2":null,
      "desp":null,
      "city":"dubai",
      "address2":"Marriott Hotel - Marina",
      "contact":"+97143194000",
      "happy_hours":"Saturday to Thursday: discounts on selected beverages",
      "dress_code":"Smart Casual",
      "check_in":"2",
      "photos":[
         {
            "Id":"50",
            "venu_id":"29",
            "photo":"1411028071.jpeg"
         },
         {
            "Id":"51",
            "venu_id":"29",
            "photo":"14110280711.jpeg"
         },
         {
            "Id":"52",
            "venu_id":"29",
            "photo":"14110280712.jpeg"
         }
      ],
      "hours":[
         {
            "Id":"1196",
            "venu_id":"29",
            "day_id":"Everyday",
            "time_id":"12.30pm - 1am"
         }
      ],
      "ratings":[

      ],
      "categories":[
         {
            "venue_id":"29",
            "cat_id":"4",
            "status":"0"
         },
         {
            "venue_id":"29",
            "cat_id":"5",
            "status":"0"
         }
      ]
   },
   "name":"The Observatory",
   "location":{
      "latitude":"25.0877",
      "longitude":"55.1462"
   },
   "address":"Marriott Hotel - Marina",
   "summary":"Enticing. Tempting. Engaging. A feast for the eyes, the warm woods, custom lighting and modern décor help create the perfect setting for a dinner party with friends or business partners. With imposing views across Dubai, The Observatory is an audacious host. \n\nUnforgettable in its style and undeniable in its energy, The Observatory’s dynamic libations and cosmopolitan ambiance are as welcomed as the modish, melodious setting. As Dubai Marriott Harbour’s definitive destination venue, The Observatory serves up more than signature dishes and cocktails; it’s the ultimate night out.\n\n\n\n\n",
   "city":"dubai",
   "cities":[
      "dubai"
   ],
   "contact":"+97143194000",
   "dressCode":"Smart Casual",
   "happyhours":[
      {
         "description":"Saturday to Thursday: discounts on selected beverages"
      }
   ],
   "ladiesnights":[

   ],
   "photos":[
      "1411028071.jpeg",
      "14110280711.jpeg",
      "14110280712.jpeg"
   ],
   "opening":[
      {
         "day":"Everyday",
         "hours":"12.30pm - 1am"
      }
   ],
   "categories":[
      "4",
      "5"
   ]
}
```

**Comment by Urigo** [comment] 2015-03-02 05:26
@Xample We've understood the difference and we found a few solutions, you can look at the different branches.
We are going to test them soon and update with the best one

**Comment by netanelgilad** [comment] 2015-03-02 06:18
Another thing you should notice is that the default  behavior in the new collection is to auto bind for changes. If you do not need that feature it will greatly improve your performance. 
@Urigo should we consider making it not the default?

**Comment by Urigo** [comment] 2015-03-02 06:22
No I don't think so.
Have you seen my solution?

**Comment by Urigo** [comment] 2015-03-02 20:31
@Xample , while we are getting ready to release a new version that helps a lot in performance, looking at your code, it isn't even related to that.
The reason is that the default of the library is now autobind and default before (and in your code) is not to autobind.

So the solution for your problem is to simply pass a false in the second parameter, like that:

    scope.bindingName = $meteor.collection(aCollection, false);

Closing this now, please re-open the problem still persist.

I will also update this issue when we get the new release although it's a different thing.

**Closed by Urigo** 2015-03-02 20:31 UTC

**Comment by Xample** [comment] 2015-03-03 08:43
Good job guys ;-)

**Comment by Urigo** [comment] 2015-03-03 10:19
@Xample did it worked for you?

**Comment by Xample** [comment] 2015-03-03 10:21
@Urigo using "false" as the parameter solved it, it is fluid again. I will check the new version one once released (if it is not the case already)
