### ISSUE TITLE
onAfterAction running twice

### ISSUE THREAD

**Issue by barbatus** [Urigo/angular-meteor#154] opened 2015-01-19 22:18 UTC
(not sure if this issue has already been here, sorry if yes)
I bumped into an issue where onAfterAction runs twice making Angular to compile a page twice (which 
happens in urigo:angular.js file's onAfterAction). I think the issue is in IronRouter's waitOn method - whenever a router has it each onAfterAction will run twice: one when router is in not ready state and one when it's ready. Would it make sense to check if Router.current().ready() in Router.onAfterAction and return if not?
So final code could look like this:
```
if(typeof Router != 'undefined')  {
      Router.onAfterAction(function(req, res, next) {
        if (!Router.current().ready()) return;
        Tracker.afterFlush(function() {
          $compile($document)($rootScope);
          if (!$rootScope.$$phase) $rootScope.$apply();
        });
     });
}
```
What do you think?
Thanks

**Comment by Urigo** [comment] 2015-01-21 06:04
OK, can you create a repo that reproduce it?
Also, if you already found a solution, a pull request will be great and will give you the credit you deserve..

**Comment by barbatus** [comment] 2015-01-22 18:05
BTW, do you plan to support IronRouter in the future?
I didn't found any information about it in the tutorial (and as I remember there was some info initially).
I just fixed this issue by substituting waitOns with subscriptions on the server side by using FastRender routes API (https://github.com/meteorhacks/fast-render#using-fast-renders-route-apis).
So I am wondering if it's worth to fix at all.

**Comment by Urigo** [comment] 2015-02-04 10:53
@barbatus I think that there is no reason why not too,  are you thinking about pull requesting it with your first solution?

**Comment by barbatus** [comment] 2015-02-07 23:26
@Urigo I actually hurried up with that fix. It doesn't work, well, at least in 100% cases. The reason here is in 'Loading' layout which can be quite complex and contain Angular code (it's actually my case too: I have <header> with Angular, for example), so it won't be compiled while it's loading if to check whether that route is ready or not.

So, to be honest, I don't know at the moment how to fix it 100%. I'd advise to use FastRender's server API as now as a workaround for everyone who wants to use waitOns (which is totally makes sense by itself).

**Comment by Urigo** [comment] 2015-02-08 08:36
@barbatus let work together on a repo the reproduces this, it will help me understand better and find a solution

**Comment by Urigo** [comment] 2015-02-17 22:32
@barbatus if you can't reproduce I don't mind setting up a meeting

**Comment by Urigo** [comment] 2015-02-19 23:41
no reproduction.
Closing.

**Closed by Urigo** 2015-02-19 23:41 UTC

**Comment by barbatus** [comment] 2015-02-20 13:39
Sorry for delays, was busy.
Here is repo with reproduction https://github.com/barbatus/ng-meteor-double-compilation
If you run it you will see 'I am HeaderController' and 'I am FooterController' appear twice and 'I am MainPageController' ones. Which means some part of every route layout are compiled twice,
I expected all angular expression should be compiled once per route.

**Comment by Urigo** [comment] 2015-02-20 21:58
@barbatus yes now I see.
So it looks like rendering twice is necessary, otherwise how will you handle the loading template with Angular?
@stlouisweb what are you thoughts on that?

**Comment by barbatus** [comment] 2015-02-20 22:15
@urigo I suggest if it was possible to take part that's been just inserted by IronRouter that we could compile whole layout when router is not ready and then compile separately newly inserted part at the moment router is ready. It needs some investigation, though. So I am going to look inside IronRouter briefly and hopefully find answer.

**Comment by Urigo** [comment] 2015-02-20 23:12
@barbatus I've done something, but I'm not sure it changed you demo, maybe it's because you have only one route?

**Comment by barbatus** [comment] 2015-02-21 14:31
@Urigo  What's you've done? It doest matter how much routes are there, IronRouter always runs onAfterAction twice if a subscription is new or with other params.

**Comment by Urigo** [comment] 2015-02-23 03:36
Yes I understand.

I've done what you said - if the route is ready, compile only the current template, when it's not, compile all

**Comment by barbatus** [comment] 2015-02-23 11:01
@Urigo Ah, I see now. It sounds like a fix. I am going to test it, if I find any issue with it I'll update here.

**Comment by barbatus** [comment] 2015-02-25 20:55
@Urigo I've tested it and it didn't work. You are actually compiling again whole layout when take currentRoute._layout_.view. Secondly, currentRoute.ready() is reactive, so, it makes onAfterAction rerun. So I tried some thing else, pls, check this branch https://github.com/barbatus/angular-meteor. Sadly, it doesn't work as well: so for some strange reason, from time to time, those regions are compiled already to the moment route is ready; it seems to be when data has been loaded very fast from server.
I'll continue looking at it in spare time, but now I am not sure it's fixable at all.

**Comment by barbatus** [comment] 2015-02-28 16:13
@urigo Check it out https://github.com/barbatus/angular-meteor, it seems work in that version.
Looks hacky though; ur decision whether makes sense to commit or not.

**Comment by Urigo** [comment] 2015-02-28 19:54
@barbatus the attributes you added are just yours right?

**Comment by barbatus** [comment] 2015-02-28 23:01
@Urigo yes, I've added _done and _docCompiled, its explained partly in the comments.

**Comment by Urigo** [comment] 2015-03-01 04:13
@barbatus ok so send a pull request and I'll add that.
Also, might be nice parameters to add to Blaze as well for other use cases, I would suggest maybe additionally pull request to add something similar to Meteor

**Comment by barbatus** [comment] 2015-03-04 18:22
Not sure what you meant by Blaze parameters. If you don't like those auxiliary fields (with underscore) i can use IronRouter's state variables instead (like this.router.state.set('_done', true))

**Comment by Urigo** [comment] 2015-03-05 00:41
WIll it create the same effect?
looks less intrusive to me

**Comment by barbatus** [comment] 2015-03-05 14:49
@urigo yes, see committed changes
