### ISSUE TITLE
Cannot import some libraries

### ISSUE THREAD

**Issue by andresespinosapc** [Urigo/angular-meteor#1415] opened 2016-08-10 13:20 UTC
I have installed dropzone via npm and I can't import it. I use `import {Dropzone} from 'dropzone';`. If I make `console.log(Dropzone)` it logs `undefined`. I've also tried other ways of importing, but I think this should be the right one. I also have issues with libraries that integrate with jquery, using syntax like `$('#myId').libraryFunction()`.

**Comment by mackbrowne** [comment] 2016-08-23 23:30
Having the same issue with several npm packages.  

I've tried ngTagsInput, angucompleteAlt with no success.  The only one I've found that works so far is angular-moment.

**Comment by mackbrowne** [comment] 2016-08-23 23:49
A bit more information here.  

First i run `meteor npm install` and get the package I want, in this case its angucomplete-alt.

Then I add `import angucompleteAlt from 'angucomplete-alt';` causing no errors.

Try adding angucompleteAlt to 

`
export default angular.module(name, [
    angularMeteor,
    uiRouter,
    angucompleteAlt
  ])
`

This throws a super nasty error linking to [This page](https://docs.angularjs.org/error/ng/areq?p0=module&p1=not%20a%20function,%20got%20undefined%20at%20http:%2F%2Flocalhost:3000%2Fpackages%2Fmodules.js%3Fhash%3D31b1491c81555082276fbfe945adc053eba0713c:804:12%20at%20assertArg%20(http:%2F%2Flocalhost:3000%2Fpackages%2Fmodules.js%3Fhash%3D31b1491c81555082276fbfe945adc053eba0713c:2628:11)%20at%20assertArgFn%20(http:%2F%2Flocalhost:3000%2Fpackages%2Fmodules.js%3Fhash%3D31b1491c81555082276fbfe945adc053eba0713c:2638:3)%20at%20http:%2F%2Flocalhost:3000%2Fpackages%2Fmodules.js%3Fhash%3D31b1491c81555082276fbfe945adc053eba0713c:5362:11%20at%20forEach%20(http:%2F%2Flocalhost:3000%2Fpackages%2Fmodules.js%3Fhash%3D31b1491c81555082276fbfe945adc053eba0713c:1057:20)%20at%20loadModules%20(http:%2F%2Flocalhost:3000%2Fpackages%2Fmodules.js%3Fhash%3D31b1491c81555082276fbfe945adc053eba0713c:5337:5)%20at%20http:%2F%2Flocalhost:3000%2Fpackages%2Fmodules.js%3Fhash%3D31b1491c81555082276fbfe945adc053eba0713c:5354:40%20at%20forEach%20(http:%2F%2Flocalhost:3000%2Fpackages%2Fmodules.js%3Fhash%3D31b1491c81555082276fbfe945adc053eba0713c:1057:20)%20at%20loadModules%20(http:%2F%2Flocalhost:3000%2Fpackages%2Fmodules.js%3Fhash%3D31b1491c81555082276fbfe945adc053eba0713c:5337:5)%20at%20http:%2F%2Flocalhost:3000%2Fpackages%2Fmodules.js%3Fhash%3D31b1491c81555082276fbfe945adc053eba0713c:5354:40).

The error i get in terminal is 

> modules.js?hash=31b1491…:804 Uncaught Error: [$injector:modulerr] Failed to instantiate module flashcard due to:
Error: [$injector:modulerr] Failed to instantiate module questionDetails due to:
Error: [$injector:modulerr] Failed to instantiate module undefined due to:
Error: [ng:areq] Argument 'module' is not a function, got undefined

**Comment by pbastowski** [comment] 2016-08-24 15:00
Have you tried this?

    export default angular.module(name, [ angularMeteor.name, uiRouter.name, angucompleteAlt.name ])

**Comment by mackbrowne** [comment] 2016-08-24 15:29
Hi @pbastowski , I'll try it right now.  WIll get back to you in a few minutes. But from what I've read that would be the syntax for angular2?  I believe this thread is for angular1

**Comment by Tallyb** [comment] 2016-08-24 15:36
@mackbrowne your problem is on Angular 1, right? (as per the errors). 
@pbastowski  response is for Angular 1. 

An alternative way might be 
  ```
import 'angucomplete-alt' ;
angular.module('app', ['angucompleteAlt ']) //name of module as string! 
```

**Comment by pbastowski** [comment] 2016-08-24 15:58
Yes, this is for AngularJS 1.x.  If you want to use module name strings then this is what you need to do

    angular.module(name, [ 'angular-meteor', 'ui.router', 'angucomplete-alt' ]) 

And `name` must of course hold  your app name.

**Comment by mackbrowne** [comment] 2016-08-24 16:15
@Tallyb you are my hero!  Thank you.  Wasted a day trying to figure this out.

This works.

`
import angular from 'angular';
import angularMeteor from 'angular-meteor';
import uiRouter from 'angular-ui-router';
import ngTagsInput from 'ng-tags-input';

const name = 'sampleComponent';
export default angular.module(name, [
    angularMeteor,
    uiRouter,
    'ngTagsInput'
  ])
`

Is this a bug?  Should we add this to documentation or tutorials somewhere?


Also thank you @pbastowski for taking a look.  Using `'angucomplete-alt'`  instead of the module name `'angucompleteAlt'` resulted in an error.  Sadly the only thing that seems to work properly is the module name as a string.

Thanks again everyone!

**Comment by mackbrowne** [comment] 2016-08-24 16:24
@Tallyb @pbastowski, what would you recommend for importing the css from node_modules?  What would be the best practice here?

**Comment by Tallyb** [comment] 2016-08-24 16:30
@mackbrowne  at the top of one of your files (index.js is a good option), just place: 
`import 'angular-material/angular-material.css';`
(but note that this is for css only, not files that require pre processing - less, sass). 

As for your first question, I belive it is not a bug but an incompatibility on the import / export between AMD (? UMD? require? - I bet @pbastowski  will know better...) and ES6 import / export. 
Nothing to do with meteor, but just with angular1.

**Comment by mackbrowne** [comment] 2016-08-24 16:39
I see.  Ahh yes!  I now see where bootstrap is importing the css.  To me this solution feels not quite like the meteor-way.  Again is this just an angular1 issue?  Does angular2 handle this better with meteor?  Npm is great because your usually getting the most up-to-date stuff, but looking at this, atmosphere has its advantages.

**Comment by pbastowski** [comment] 2016-08-24 17:19
@mackbrowne Angular2 does not handle this any better, because, it is not related to angular. @Tallyb is correct in that it is related to the ES6 import statements. "imports" statements are transpiled into JavaScript 5.1 code that makes calls to the module loader (require), which in turn is provided by Meteor. This whole deal with module loaders is a complex thing in itself, if you have a read of the various threads.

So, for now there are just know ways to get things working. And we live with that :)

It is also a good observation that sometimes Meteor packages are better suited, under certain conditions, then NPM packages.

Also, strange that the "angucomplete-alt" did not work, because their own github repo README says to use this string, see https://github.com/ghiden/angucomplete-alt.

**Comment by mackbrowne** [comment] 2016-08-24 17:27
@pbastowski you are completely correct, It seemed I had a bit of typo when trying.

And yeah I found an issue on the main meteor repo saying they aren't super happy with how its being handled still.  The issue has been closed and re-opened many times.  Maybe one day it will be fixed, but for now I agree and am happy to just be developing again.

Thanks again!

**Closed** 2016-10-16 09:44 UTC
