### ISSUE TITLE
There is no template with the name 'loginButtons' when using ian:accounts-ui-bootstrap-3

### ISSUE THREAD

**Issue by ruchevits** [Urigo/angular-meteor#455] opened 2015-06-19 23:41 UTC
I've removed 'accounts-ui' and installed 'ian:accounts-ui-bootstrap-3' instead.

For some reason the appropriate template can't be found. It works when including using Meteor-style {{> loginButtons}}. Where the problem could be?

**Comment by Urigo** [comment] 2015-06-21 19:33
Duplicate of https://github.com/Urigo/angular-meteor/issues/191

**Closed by Urigo** 2015-06-21 19:33 UTC

**Comment by carlosbaraza** [comment] 2015-12-08 03:22
@ruchevits I just created a small wrapper around `ian:accounts-ui-bootstrap-3` that does not require the use of Blaze or `templating` in your main package. Hopefully, this will help you with your issue or give you an idea of how I solved it.

https://github.com/carlosbaraza/accounts-ui-bootstrap-3-angular
