### ISSUE TITLE
Query with sort - Variable undefined after update

### ISSUE THREAD

**Issue by muehle28** [Urigo/angular-meteor#1125] opened 2016-01-23 11:10 UTC
Hello,

I'm using Angular2 with Meteor. I do a query with sort followed by an update of the sortOrder variable of one Item, so that it flips position with another. Then I'm getting following error: Cannot read property 'name' of undefined. If the position stays the same and the sortOrder variable changes everything works fine. Also Inserts are working correctly.
```javascript
this.items = Items.find( { }, { sort: { 'sortOrder':1, 'name':1 }});
```
```html
<ul>
  <li *ngFor="#item of items">{{item.name}} - 
      <input #sortOrder type='number' (onChange)="saveSortOrder(item._id, sortOrder.value)">
  </li>
</ul>
```
```javascript
saveSortOrder(id, value){
  Items.update({ _id: id }, { $set: { sortOrder: value }});
}
```
Thanks
Michael

**Comment by kazkis** [comment] 2016-01-29 11:36
Hi,
I think I have run into the same problem. I tried to look for help about two weeks ago [here](http://stackoverflow.com/questions/34818585/angular2-meteor-variable-undefined-after-a-find-with-sort-in-a-subscribe-fun) on Stackoverflow but no one has been able to help me ( I also included a sample project to replicate the problem).

**Comment by kazkis** [comment] 2016-02-08 11:48
Updating the angular2-meteor package to the latest version (currently 0.4.2) fixed this issue for me.

**Comment by Urigo** [comment] 2016-02-12 15:13
@kazkis thanks for updating.
Closing, please re-open or comment and tag me if the problem persists.

**Comment by kazkis** [comment] 2016-02-12 15:36
@Urigo Just to be sure I tried again today with the same project I posted on stackoverflow and the problem is sadly still here (I didn't notice there was still a workaround in the original code). I'm sorry for the confusion.

**Comment by Urigo** [comment] 2016-02-17 23:10
@kaihaase can you please try the new `1.3.6` version?
If it doesn't work for you can you please provide a simple reproduction project?

**Comment by Urigo** [comment] 2016-04-10 22:29
closing as there is no reproduction with the new version.
If it still persists, please re-open and tag me
thanks

**Closed by Urigo** 2016-04-10 22:29 UTC
