### ISSUE TITLE
loginButtons template not found with accounts-ui-bootstrap-3

### ISSUE THREAD

**Issue by nickjanssen** [Urigo/angular-meteor#191] opened 2015-02-19 11:41 UTC
Hi Urigo, thank you so much for putting this framework together, I'm really enjoying it so far!

I've tried to use a loginButtons template from another UI package: https://atmospherejs.com/ian/accounts-ui-bootstrap-3

So I'm doing `<meteor-include src="loginButtons"></meteor-include>`

But for some reason, the console tells me:
``` meteorTemplate: There is no template with the name 'loginButtons'```
Any ideas? If I include it using the Meteor syntax it works fine, e.g. ```{{> loginButtons}}```

**Comment by Urigo** [comment] 2015-02-19 20:29
Can you create a reproduction?
I will have a look now

**Comment by Urigo** [comment] 2015-02-19 23:38
@nickjanssen looking at the code, it looks like in the regular accounts ui the name of the loginButtons template is:

    name: loginButtons

And in your library it is:

    name _loginButtons

Also looking at the source code, here is Meteor one:
https://github.com/meteor/meteor/blob/devel/packages/accounts-ui-unstyled/login_buttons.js#L5
and here is their one:
https://github.com/ianmartorell/meteor-accounts-ui-bootstrap-3/blob/master/login_buttons.js#L13

I don't know why they did that but you can solve it easily like that:

    <meteor-include src="_loginButtons"></meteor-

I would also open an issue there, asking them why did they do that.

Closing as it doesn't look like an angular-meteor problem

**Closed by Urigo** 2015-02-19 23:38 UTC

**Comment by nickjanssen** [comment] 2015-02-19 23:55
Awesome, thank you! One question, are there any downsides if I use the regular `{{> loginButtons}}`  instead of `<meteor-include src="_loginButtons"></meteor-include>`? It seems to work fine using the Meteor syntax.

**Comment by Urigo** [comment] 2015-02-19 23:58
As long as you are inside a regular .html file there is no difference.

But if you are using .tpl (next release will be changed to .ng.html) then only the <meteor-include> will work

**Comment by funkytaco** [comment] 2015-07-14 18:47
>then only the will work

Can you clarify which will work? That's an incomplete sentence. I'm running into a problem where I removed loginButtons meteor include and the .ng.html page is not recompiling to remove it...

**Comment by estaub** [comment] 2015-08-27 18:36
I see the same issue, FWIW.  Adding the underscore works.  I wonder if there's leading-underscore adding/stripping somewhere in Spacebars or related.

**Comment by DevinXian** [comment] 2015-09-10 04:48
`<meteor-include src="loginButtons"></meteor-include>`
or
`<meteor-include src="_loginButtons"></meteor-include>`
not works.
However,`<blaze-template name="_loginButtons"></blaze-template>` is OK :)

**Comment by borisfeldmann** [comment] 2015-10-13 04:51
@DevinXian: Thanks for pointing this out. 

But when I user '<blaze-template name="_loginButtons"></blaze-template>' the '<blaze-template>' tag is included in the rendered output, between my '<ul>' and loginButton's '<li>' tag. 

Is there a way to prevent this and get a clean '<ul><li>' strutcture?

**Comment by gscalise** [comment] 2015-10-16 13:21
@borisfeldmann I'm having the same problem as you. Were you able to fix it?

**Comment by carlosbaraza** [comment] 2015-12-08 03:20
@borisfeldmann @gscalise I just created a small wrapper around `ian:accounts-ui-bootstrap-3` that does not require the use of Blaze or `templating` in your main package. Hopefully, this will help you with your issue or give you an idea of how I solved it.

https://github.com/carlosbaraza/accounts-ui-bootstrap-3-angular
