### ISSUE TITLE
(v1.3.4) $auth.currentUser doesn't seem to work

### ISSUE THREAD

**Issue by eugenious** [Urigo/angular-meteor#1064] opened 2016-01-05 17:11 UTC
I put some comments in a closed issue which I probably shouldn't have done:
#968

I'm having trouble getting $auth.currentUser to work, I'm not sure if it's a bug or I'm doing something wrong.

I've copy-pasted here the relevant bits:

Thanks for the great work. I think this is heading in the right direction. If I understand correctly, I should be able to use the $auth service to replace the Meteor global variable. That sounds like a good approach, so here's what I did:

This is what I had previously (it works fine):
```js
    controller: function($scope) {
      $scope.helpers({
        isLoggedIn() {
          return Meteor.userId() !== null;
        }
      });
    }
```

Using the new $auth service:
```js
    controller: function($scope, $auth) {
      $scope.helpers({
        isLoggedIn() {
          return angular.isDefined($auth.currentUser);
        }
      });
    }
```

I must be missing something, because I can't get this to work:

* isLoggedIn always returns `false`, regardless if a user is logged in or not
* doesn't seem to be reactive either

By the way, and this might not be related to the issue, I noticed that $scope.$auth.currentUser is returning the correct user (reactively), however I didn't even expected $scope.$auth to be defined at all since I hadn't defined it.

What am I doing wrong?

**Comment by dotansimha** [comment] 2016-01-06 19:53
@eugenious 
Hi, seems like you are right, I think that a bug causes that `$auth.currentUser` is only exposed to the view (in `$scope.$auth` object).
I am checking it now and will update later.

**Comment by Urigo** [comment] 2016-01-09 12:50
@eugenious why would you need to use `$auth.currentUser` in scope helpers and not just `Meteor.user` ?

**Comment by MilosStanic** [comment] 2016-01-09 22:16
I confirm that $auth.currentUser is only exposed to view, but not to controller. In controller it's undefined. 
Is this going to be fixed in next release?

**Comment by eugenious** [comment] 2016-01-11 14:33
@Urigo I was thinking that using $auth was better than relying on a global Meteor object. (For ease of unit testing, for example). To quote the [documentation](http://www.angular-meteor.com/api/1.3.2/auth):

> $auth wraps Meteor's API for ease of use with AngularJS applications

So I thought I would try it because further down on the page, the documentation reads:

> $auth.currentUser is a property of the $auth service, which contain the current logged in user in every time.

But I couldn't get it to work.

**Comment by sean-stanley** [comment] 2016-01-15 04:50
+1 Meteor.user() did work though

**Comment by DAB0mB** [comment] 2016-01-15 17:03
Here are three alternatives to do so:

```js
function MyCtrl($scope) {
  $scope.helpers({
    isLoggedIn() {
      return !!Meteor.user();
    }
  });
}

function MyCtrl($scope) {
  $scope.helpers({
    isLoggedIn() {
      return !!$scope.$auth.currentUser;
    }
  });
}

function MyCtrl($reactive, $scope) {
  $reactive(this).attach($scope);
  
  this.helpers({
    isLoggedIn() {
      return !!this.auth.currentUser();
    }
  });
}
```

There is no need to define `currentUser` on `$auth` service since you can get it using `Meteor.user`.

**Comment by Urigo** [comment] 2016-01-15 17:04
Thanks @DAB0mB

**Closed by Urigo** 2016-01-15 17:04 UTC

**Comment by sean-stanley** [comment] 2016-01-15 19:42
Hang on, can helpers return non cursor values? The documentation says that
a helper function must return a MongoDB cursor. Maybe it should be updated
if the suggested workarounds are best practice methods.

**Comment by eugenious** [comment] 2016-01-18 03:08
@DAB0mB, these are all reasonable *workarounds*, however they are not ideal because:
1. relies on a global Meteor variable, not great
2. relies on a $scope.$auth variable, which as far as I can tell, isn't documented and possibly shouldn't even be there. ($auth is a service, not a variable automatically added to the root scope??, see clarifying comment below)
3. this one is kinda funky

As far as I know, Angular services are not automatically put on the scope, it's up to the application developer to decide how to consume the service, either in a controller, in a directive's link function, within a state resolve function, etc. This means that many of the template examples given in the [documentation](http://www.angular-meteor.com/api/1.3.2/auth) won't work without a little piece of glue code, something like:

```js
function MyCtrl($scope, $auth) {
  $scope.$auth = $auth;
}
```

@Urigo If you don't plan to fix this then I think the documentation needs to be updated as it's misleading right now. It says $auth.currentUser is available, but it's not.

**Comment by MilosStanic** [comment] 2016-01-18 08:36
@Urigo @DAB0mB  I completely agree with @eugenious . 

The point of the `$auth` service is having the universal source of truth when it comes to testing whether user is logged in and what are his/her properties. Therefore, existence of `$auth.currentUser` available through `$auth` service is very useful. 

Finally, let me quote the docs: 
>`$auth` service is a part of angular-meteor-auth package, and it located inside angular-meteor.auth AngularJS module.
>
>This service provides the functionality for authentication for your app.
>
>`$auth` wraps Meteor's API for ease of use with AngularJS applications, and also provides the ability to access Meteor's Accounts package from the UI.
> ...
>`$auth.currentUser` is a property of the `$auth` service, which contain the current logged in user in every time.
>
>It automatically changes when the user logs in or logs out, and it can be used from the view or the AngularJS controller/components.

Things should be exactly as the above quoted sections of docs. 

Thanks again.

**Comment by eugenious** [comment] 2016-01-18 15:24
A small idea, now that I think about it, maybe currentUser shouldn't be a property but rather a function, thus:

    $auth.currentUser() is a getter function of the $auth service

**Comment by MilosStanic** [comment] 2016-01-18 15:44
In my opinion, it would be better if it were a reactive property.
For example, what if the user record contains user's online status. I want to be able to reactively check on that.
In fact, there can be both a getter function and a reactive property.

**Comment by mattiLeBlanc** [comment] 2016-02-07 00:40
Hi,
I might have a related issue that my controller's constructor is not consistent in resolving the currentUser.
Some reloads I get a current user, and some it is undefined. It must be a timing issue of the Users subscription but I am using several approaches like promise, Reactive variable and a resolve on the router. All display the same behaviour.

See console output:
```
globalController currentuser undefined
profile.information.controller.ts:25 $auth -> undefined
profile.information.controller.ts:36 > currentUser undefined
profile.information.controller.ts:29 $auth wait undefined
```

My constructor:
```
  constructor( private $log: angular.ILogService, private $state: angular.ui.IStateService, private $scope: any, private currentUser: any, private toastr: Toastr, $reactive: any, private $auth: any  ) {

    $reactive(this).attach($scope);
    var user: any;
    console.log( '$auth ->', $auth.currentUser);

    $auth.waitForUser().then(() => {
        let currentUser = $auth.currentUser;
        console.log( '$auth wait', currentUser );
      });
    this.autorun( () => {

      user = this.getReactively( 'currentUser' );
    });
    // var user = currentUser;
    console.log('> currentUser', user );
    if ( user ) {
      this.information = user.profile;
      this.information.companyAbn = '123 456 734';
    }
  }
```

So I am trying multiple things in there so that's why its messy.

Just another reload of the page and check console output:
```
 globalController currentuser Object {_id: "bATDodgxdCFn6tsBN", emails: Array[1], profile: Object}
profile.information.controller.ts:25 $auth -> undefined
profile.information.controller.ts:36 > currentUser Object {_id: "bATDodgxdCFn6tsBN", emails: Array[1], profile: Object}
profile.information.controller.ts:29 $auth wait undefined
```

Any idea;s?
do I need to apply a window.setTimout 0 for now?

**Comment by Urigo** [comment] 2016-02-17 22:54
should be fixed with the new `1.3.6` release.
Please re-open and tag me with a reproduction project if it's not.

**Comment by mattiLeBlanc** [comment] 2016-02-23 01:18
new issue, see: https://github.com/Urigo/angular-meteor/issues/1126#issuecomment-187115397

**Comment by sean-stanley** [comment] 2016-05-29 21:00
Hi, I found some new stuff for you, i think you're gonna like it, more info at <http://xicritothu.dandginnovations.com/lnrqw>

Cheers, Sean Stanley

**Comment by mattiLeBlanc** [comment] 2016-05-30 01:31
is this posted by a bot or is this is real URL?

**Comment by dapids** [comment] 2016-05-30 06:33
@mattiLeBlanc,

Guess it's a spambot. :/

**Comment by Urigo** [comment] 2016-05-30 07:10
it's great to get massive weight loss though...

I've edited the message so people won't click it..

**Comment by sean-stanley** [comment] 2016-08-15 16:56
Hey! 

I've  seen that interesting stuff recently, you  would  definitely  love it. Just take a look <http://movoltyfre.browsemylibrary.com/lnxjzk>

Yours, Sean Stanley

**Comment by sean-stanley** [comment] 2016-08-31 15:03
Hi! 

Our friend have written  to me  a couple of days ago, they have a surprise for you,  just  take a look <http://frusontipro.amazingwaffles.com/lnxxhwbn>

Sean Stanley

**Comment by hanselke** [comment] 2017-07-30 05:23
Hi,

ive just recently upgraded from meteor 1.2 > 1.5.6 and in the process... have moved all of my bower dependencies as well some meteor packages all to meteor npm.

Essentially, the problem is after including the $auth controller, $auth.currentUser isnt defined in my angular controllers.

I looked at the angular-meteor docs and see that 1.3.11 lists $auth 0.3.0

Problem: at https://github.com/Urigo/angular-meteor-auth
there isnt any 0.3.x tags, only 0.2.x then 1.x. I'm on 1.1.1.

Which version should I be using?
