### ISSUE TITLE
angular dirty check going crazy

### ISSUE THREAD

**Issue by boomfly** [Urigo/angular-meteor#517] opened 2015-07-15 12:37 UTC
If you switch between views which have a subscription, the refresh cycle scope values each time increases

in controller
```
$scope.$meteorSubscribe('requests-wait-list').then ->
        $scope.requests = $scope.$meteorCollection ->
          Request.find city: $scope.currentUser.profile.city
```
And even if that controller created ones and only views changed, refresh cycle loop increased anyway.

**Comment by ccortezia** [comment] 2015-07-15 12:46
Hi @boomfly, your situation seems interesting, but I am not sure I fully understood your problem. Could you try to better explain ? Perhaps you could isolate the bugged behavior on a repository so we can try to reproduce ?

**Comment by boomfly** [comment] 2015-07-15 17:06
Dont close issue tomorrow i upload on git reproduction

**Comment by ccortezia** [comment] 2015-07-15 17:21
Ok no rush. I am just trying to help.

**Comment by boomfly** [comment] 2015-07-19 06:52
Here sources: https://github.com/boomfly/AngularCrazyDirtyCheck!

Here deployed version: http://idelivery.meteor.com/#/categories!

<img width="1440" alt="2015-07-19 12 48 34" src="https://cloud.githubusercontent.com/assets/3257268/8764880/99d84d80-2e14-11e5-8c55-76625752e21d.png">

**Comment by Urigo** [comment] 2015-07-20 18:01
I ran it yet, but looks like you might get a few Angular libraries because of the bower files...
can you move them to Meteor packages?  http://angular-meteor.com/tutorial/step_19

**Comment by boomfly** [comment] 2015-07-20 21:27
There already local package named "bower" where all bower dependencies defined

https://github.com/boomfly/AngularCrazyDirtyCheck/blob/master/packages/bower/package.js#L34

And if there i define angular.js file then i got this warning:

```
WARNING: Tried to load angular more than once.
```

<img width="1440" alt="2015-07-21 2 37 43" src="https://cloud.githubusercontent.com/assets/3257268/8787836/3572d438-2f58-11e5-8cc5-8d3e7c34e44c.png">

**Comment by DAB0mB** [comment] 2015-09-04 13:01
@boomfly can you please create a more concise repository that demonstrates your issue? (This)[https://github.com/boomfly/AngularCrazyDirtyCheck] repository doesn't seem to work.

**Comment by Urigo** [comment] 2015-09-09 18:41
@boomfly please provide an updated example?
Closing for now

**Closed by Urigo** 2015-09-09 18:41 UTC
