### ISSUE TITLE
angular-meteor 1.3.5 log in

### ISSUE THREAD

**Issue by ThomsC** [Urigo/angular-meteor#1108] opened 2016-01-16 11:31 UTC
After upgrading to 1.3.5 I got some problems with the current user.

Just after log in I do a `state.go` and the state is running some subscriptions but as they need the current user in server side to protect the data I got no result.

I need to refresh the page to get the datas which is not very convenient but sometimes it doesn't work...

The tricky part was when the state's controller was loading I printed the current user ID on the client to see what was happening and it was not undefined!

I got no problems at all with 1.3.4

**Comment by burock** [comment] 2016-01-16 15:15
+1

**Comment by plantsmiles** [comment] 2016-01-21 14:41
I've experienced a very similar thing. If i do the normal flow, login -> redirect to other page -> and then ask for Meteor.user() or Meteor.userId() it `usually` works.  But when i'm doing testing on that page where the page gets refreshed a lot, those methods don't work.  I realize I'm just testing...but its not *that* far fetched that a user would just do a simple refresh on that page, which would break some things.

+1

**Comment by kusmierz** [comment] 2016-01-27 22:13
+1

**Comment by ozsay** [comment] 2016-01-28 10:46
@ThomsC Can you provide a repository for reproduction?

**Comment by kusmierz** [comment] 2016-01-28 11:03
dunno if the problem is the same, but I've the issue even in tutorial app

```bash
$ git clone https://github.com/Urigo/meteor-angular-socially.git
Cloning into 'meteor-angular-socially'...
remote: Counting objects: 1367, done.
remote: Total 1367 (delta 0), reused 0 (delta 0), pack-reused 1367
Receiving objects: 100% (1367/1367), 148.30 KiB | 0 bytes/s, done.
Resolving deltas: 100% (616/616), done.
Checking connectivity... done.
$ cd meteor-angular-socially/
$ git checkout step_20
(...)
$ meteor
```

Use case:

1. register
1. create at least one private party
1. logout
1. login (it should redirect you to /parties page)

works perfect. Now update things.

```
$ meteor update
This project is already at Meteor 1.2.1, the latest release.
                                              
Changes to your project's package version selections from updating package versions:
                                              
angular                               upgraded from 1.3.1 to 1.3.5
angular-meteor-data                   upgraded from 0.0.8 to 0.1.0
angularui:angular-google-maps         upgraded from 2.2.1 to 2.3.0
pbastowski:angular-babel              upgraded from 1.0.7 to 1.0.9
planettraining:material-design-icons  upgraded from 2.0.0 to 2.1.1
stevezhu:lodash*                      upgraded from 1.0.2 to 3.5.0_3
tmeasday:publish-counts               upgraded from 0.7.2 to 0.7.3

                                             
* These packages have been updated to new versions that are not backwards
compatible.
                                              
The following top-level dependencies were not updated to the very latest version available:
 * angular:angular-material 0.11.4 (1.0.3 is available)
                                              
Newer versions of the following indirect dependencies are available:
 * dburles:mongo-collection-instances 0.3.4 (0.3.5 is available)
 * lai:collection-extensions 0.1.4 (0.2.1_1 is available)
 * nmccready:angular-simple-logger 0.0.4 (0.1.7 is available)
 * stevezhu:lodash 3.5.0_3 (4.0.0 is available)
To update one or more of these packages, pass their names to `meteor update`.
```

ok, now do the same:

1. register
1. create at least one private party
1. logout
1. login again (it should redirect you to /parties page)
1. on /parties page there is NO party at all (even public ones). I could see them only after refresh

From Meteor DDP Monitor (just login at /login page):

```
calling method login with [object Object] "{"msg":"method","method":"login"," ... } 12:01:53
item added to users collection "{"msg":"added","collection":"users" ... } 12:01:54
subscription ready for undefined "{"msg":"ready","subs":["DE9BvTjeHCtG ... } 12:01:54
updated "{"msg":"updated","methods":["1"]}" 12:01:54
got result for method login "{"msg":"result","id":"1","result" ... } 12:01:54
subscribing to images with  "{"msg":"sub","id":"iLPZzQmwen8XnkPDk ... } 12:01:54
subscribing to users with  "{"msg":"sub","id":"WZ5bneo4WRY25Asxi ... } 12:01:54
subscribing to parties with [object Object],  "{"msg":"sub","id":"FeaHcXrqeXLjd44tK ... } 12:01:54
unsub "{"msg":"unsub","id":"iLPZzQmwen8XnkPDk"}" 12:01:54
unsub "{"msg":"unsub","id":"WZ5bneo4WRY25Asxi"}" 12:01:54
unsub "{"msg":"unsub","id":"FeaHcXrqeXLjd44tK"}" 12:01:54
item added to cfs.images.filerecord collection "{"msg":"added","collection":"cfs.ima ... } 12:01:54
subscription ready for images "{"msg":"ready","subs":["iLPZzQmwen8X ... } 12:01:54
subscription ready for users "{"msg":"ready","subs":["WZ5bneo4WRY2 ... } 12:01:54
item added to counts collection "{"msg":"added","collection":"counts\ ... } 12:01:54
item added to parties collection "{"msg":"added","collection":"parties ... } 12:01:54
subscription ready for parties "{"msg":"ready","subs":["FeaHcXrqeXLj ... } 12:01:54
item removed from cfs.images.filerecord collection "{"msg":"removed","collection":"cfs.i ... } 12:01:54
nosub "{"msg":"nosub","id":"iLPZzQmwen8XnkPDk"}" 12:01:54
nosub "{"msg":"nosub","id":"WZ5bneo4WRY25Asxi"}" 12:01:54
item removed from counts collection "{"msg":"removed","collection":"count ... } 12:01:54
item removed from parties collection "{"msg":"removed","collection":"parti ... } 12:01:54
nosub "{"msg":"nosub","id":"FeaHcXrqeXLjd44tK"}" 
```

What am I discovered is, when you set up timeout (ie. 200ms) on `$state.go()` at [Urigo/meteor-angular-socially](https://github.com/Urigo/meteor-angular-socially)[@step_20](https://github.com/Urigo/meteor-angular-socially/tree/step_20)[/client/auth/login/login.component.js#L22](https://github.com/Urigo/meteor-angular-socially/blob/step_20/client/auth/login/login.component.js#L22), it will work correctly...

**Comment by kamilkisiela** [comment] 2016-01-28 11:03
@ThomsC Could you look into developer tools (`Network` tab in Chrome) and check websocket connection? 

Make a quick scan, check if there is `SUB` action for proper subscription (exactly the same as you mentioned, that one with `this.userId` condition.

**Comment by kamilkisiela** [comment] 2016-01-28 11:04
@kusmierz I think a little workaround for that would be wrapping `this.subscribe()` in `$timeout`.

Could you say if it solves a problem?

**Comment by ozsay** [comment] 2016-01-28 11:41
@kamilkisiela I didn't have to logout and login. I registered, created a private party and it didn't show up. Can you check if register and create a private party works for you (after update).

**Comment by kamilkisiela** [comment] 2016-01-28 11:45
@ozsay Ok, i'm going to look at it in a moment.

**Comment by kamilkisiela** [comment] 2016-01-28 11:57
@ozsay Doesn't work.

**Comment by ozsay** [comment] 2016-01-28 12:48
It looks like in the newer version there are alot of `unsub` messages to the server. Will check what is going on

**Comment by kamilkisiela** [comment] 2016-01-28 12:55
@ozsay I'm currently looking into it. I can't work right now because of it :)

Tracker computation of subscription is `invalidated` and i'm seeking the reason.

**Comment by kamilkisiela** [comment] 2016-01-28 13:44
@ozsay Subscriptions work fine but only when there is no cursor in helpers.

Something like this won't work.

```javascript
this.subscribe(...);
this.helpers({
  items() { return Items.find(); } 
});
```

But this will.
```javascript
this.subscribe(...);
```

**Comment by pacozaa** [comment] 2016-01-29 12:18
+1 looking forward for solution.

Should I switch back to 0.0.9?

**Comment by kamilkisiela** [comment] 2016-01-29 12:23
I switched back to 0.0.9 and it works fine

pt., 29.01.2016, 13:18 pacozaa użytkownik <notifications@github.com>
napisał:

**Comment by pacozaa** [comment] 2016-01-29 12:50
@kamilkisiela I don't have angular-meteor-data package. so which one I should switch back?
![stategoissue](https://cloud.githubusercontent.com/assets/3154089/12675996/2171f5e4-c6c1-11e5-8ac2-4fdefd5425d0.PNG)

**Comment by pacozaa** [comment] 2016-01-29 12:53
@kusmierz  I follow your instruction

`    setTimeout(function(){
               $state.go('somestate');
             }, 200);   `

and it works fine!

**Comment by ozsay** [comment] 2016-02-03 13:31
@kamilkisiela @pacozaa @ThomsC @burock 

The issues with `socially` seems to be fixed with 1.3.6.

Can you test it in your projects to see if any other issues raise?

we haven't published it yet so you'll need to run it locally (I explained it [here](https://github.com/Urigo/angular-meteor/issues/1105#issuecomment-179228637)).

Thanks

**Comment by Urigo** [comment] 2016-02-12 23:56
`angular@1.3.6-beta.1` was released.
Please check and let me know if that fixed the issue.

**Comment by ThomsC** [comment] 2016-02-13 10:17
It is not fixed.

Just after loggin I get no data from any subscriptions. But I can go inside the application.

When I try to go to an other page and check in the resolve if there is a user. This function get call every time. So I can't move in my application. Always redirect me in the loggin page..

```javascript
function stateChange($rootScope, $state, $stateParams, $meteor, blockSettings, blockMenu) {

        $rootScope.$on('$stateChangeError', function (event, toState, toParams, fromState, fromParams, error) {
            if (error === "AUTH_REQUIRED") {
                console.log('No user');
                $state.go(blockSettings.pageLogin);
            }
        });
    }
```

I can't share a repo as if it's a company application... Go back to 1.3.4

**Comment by Urigo** [comment] 2016-02-13 11:41
@ThomsC what version of the [angular-meteor-auth](http://www.angular-meteor.com/api/1.3.6/auth) package are you using?

**Comment by Urigo** [comment] 2016-02-13 11:41
also, can you show me your routes file?

**Comment by ThomsC** [comment] 2016-02-13 12:54
I did a meteor update so I had everything to the last version I suppose.

Here is the type of subscription I use juste after loggin which doesn't work with 1.3.6 :

```javascript
        this.subscribe('userInfo');

        this.helpers({
            userInfo: () => {
                return UsersInfos.findOne({owner_id:Meteor.userId()});
            }
        });
``` 

I've juste check the documentation http://www.angular-meteor.com/api/1.3.6/auth

For now I use $auth.requireUser() but maybe I should rewrite it

```javascript
resolve: {
                    user: ['$auth', '$state', 'blockSettings', function ($auth, $state, blockSettings) {
                        return $auth.requireUser().then(function (user) {
                            if(user){
                                if (!Roles.userIsInRole(Meteor.userId(), ['user', 'sub-user'])){
                                    Meteor.logout();
                                    console.log('user as no rights');
                                    $state.go(blockSettings.pageLogin);
                                }
                                else {
                                    return user;
                                }
                            }
                        });
                    }]
                }
```

I prefer to use `resolve` to check if an user has any right instead of doing it in the controller. Is it still possible to do it? Can we still use `$auth.requireUser()` ?

**Comment by Urigo** [comment] 2016-02-13 14:12
`meteor update` is not enough yet because the version is still in beta.
you should do `meteor update angular@1.3.6-beta.1` in order to use the new version.
some with `angular-meteor-auth` - `meteor update angular-meteor-auth@0.2.0-beta.1`

About using un the `resolve` yes you can still do that and I should add it to the docs - just use [$$Auth.$awaitUser](http://www.angular-meteor.com/api/1.3.6/auth)

also, please provide your routes file, I think there might be a mistake there

**Comment by ThomsC** [comment] 2016-02-13 14:21
What part exactly are you interested in the routes file?

Because I don't have one config.route.js file I use the John papa guide so I have multiple files. 

Ok I'll redo a test with your recommandation.

And what about the subscription ?

**Comment by Urigo** [comment] 2016-02-13 14:22
I'm interesting in the Login route definition.
the subscription should work, isn't it?

**Comment by ThomsC** [comment] 2016-02-13 14:31
With 1.3.4 the subscription works not with 1.3.6

Here is a part of my route file with the abstract route then every other route use the resolve method I show before.

```javascript
(function () {
    'use strict';

    angular
        .module('app')
        .config(moduleConfigLayoutDashboard)
        .run(stateChange);

    stateChange.$inject = ['$rootScope', '$state', '$stateParams', '$meteor', 'blockSettings', 'blockMenu'];

    function stateChange($rootScope, $state, $stateParams, $meteor, blockSettings, blockMenu) {

        $rootScope.$on('$stateChangeError', function (event, toState, toParams, fromState, fromParams, error) {
            if (error === "AUTH_REQUIRED") {
                console.log('Utilisateur absent');
                $state.go(blockSettings.pageLogin);
            }
        });
    }

    moduleConfigLayoutDashboard.$inject = ['$stateProvider'];

    function moduleConfigLayoutDashboard($stateProvider) {

        $stateProvider
            .state('dashboard-default.premium', {
                abstract: true,
                views: {
                    sidebarLeft: {
                        templateUrl: 'client/app/Application/blocks/components/menu/menu.ng.html',
                        controller: 'MenuController',
                        controllerAs: 'vm'
                    },
                    toolbar: {
                        templateUrl: 'client/app/Application/blocks/components/toolbar/toolbar.ng.html',
                        controller: 'DefaultToolbarController',
                        controllerAs: 'vm'
                    },
                    sidebarRight: {
                        templateUrl: 'client/app/Application/blocks/components/notifications-panel/notifications-panel.ng.html',
                        controller: 'blockNotificationsPanelController',
                        controllerAs: 'vm'
                    },
                    content: {
                        template: '<div id="admin-panel-content-view" class="{{layout.innerContentClass}}" flex ui-view="main"></div>'
                    },
                    below: {
                        templateUrl: 'client/app/Application/blocks/layouts/dashboard/dashboard-default/below-content.ng.html'
                    }
                },
                resolve: {
                    user: ['$auth', function($auth) {
                        return $auth.requireUser();
                    }]
                }
            })
            .state('authentification', {
                abstract: true,
                templateUrl: 'client/app/Application/blocks/layouts/authentification/authentification.ng.html'
            });
    };

})();


```

**Comment by Urigo** [comment] 2016-02-13 14:39
yes thank you.
let's try to solve one problem at the time.
Can you create a simple reproduction to each problem?:
1. subscription doesn't work
2. All routes resolves with `$stateChangeError`, even when you are logged in
Am I missing a scenario?


@kamilkisiela is your use case works with `1.3.6-beta.1`?

**Comment by ThomsC** [comment] 2016-02-13 14:42
Ok I'm sorry when I see this line `angular@1.3.6-beta.1 was released.` I thought meteor update would be enough but it's not... I was not using the good packages...

No you are not missing a scenario.

But wait probably a noob question but look 

```javascript
meteor update angular@1.3.6-beta.1
=> Errors while upgrading packages:           
                                              
While selecting package versions:
error: Package names can only contain lowercase ASCII alphanumerics, dash, dot,
or colon, not "@"
```

...?

**Comment by Urigo** [comment] 2016-02-13 15:55
can you try going into the `.meteor/packages` files and change `angular` to `angular@1.3.6-beta.1`?

**Comment by kamilkisiela** [comment] 2016-02-13 16:56
@Urigo I'm going to create repo with reproduction so expect it in a few minutes.

**Comment by kamilkisiela** [comment] 2016-02-13 17:52
@Urigo 
Here's reproduction.

https://github.com/kamilkisiela/angular-meteor-auth-repro/commits/master

Latest commit contains `angular@1.3.6-beta.` and everything work. :+1: 
Second latest contains `angular@1.3.5` and you should see there is a problem with subscription. :-1: 

Sorry for the mess but I'm short on time.

**Comment by ThomsC** [comment] 2016-02-14 16:19
ok so here is my list of package

```javascript
angular                             1.3.6-beta.1  Everything you need to use ...
angular-meteor-auth         0.2.0-beta.1  Angular-Meteor authenticati...
````

But when I try to test if everything work, all my `$state.go()` has no effect of routing anymore. so I'm block in the loggin page ... ???

I then type the URL like 'localhost/home' because even if the `$state.go()`doesn't work meteor as log me. Once the page is loaded I got a blank page, no messages  at all in the console.

So I'm wondering if there is some functions like `$auth.requireUser` that are obsolete in 1.3.6-beta.1 if so tell me because I need to rewrite everything to test it correctly.

**Comment by Urigo** [comment] 2016-02-14 16:27
@ThomsC could you try to create a separate simple repo that reproduce that scenario?
I believe that with something like that I can solve it very quickly

**Comment by burock** [comment] 2016-02-15 07:24
Hi,
I did upgrade to 1.3.6 beta, this time my subscriptions don't return anything at all.. They are actually pretty forward classic subscriptions, nothing special. 
When I downgrade to 1.3.5, subscriptions work, but first time login there's no data (as what this topic is about), so I have to refresh the page.
When I downgrade to 1.3.4 all works great..

fyi,
thanks
burak.

**Comment by ThomsC** [comment] 2016-02-15 08:24
@Urigo Ok I'll try to do it this week

**Comment by ozsay** [comment] 2016-02-15 08:33
@burock Can you provide a repo with your issue ?

Thanks

**Comment by burock** [comment] 2016-02-15 08:45
Sure, you can try it [here](https://github.com/burock/superintendent)

Thanks

**Comment by ozsay** [comment] 2016-02-15 09:58
@burock it's a whole application :), can you provide the scenario as well so I could reproduce it?

**Comment by burock** [comment] 2016-02-15 10:08
sure :) , sorry..

**Comment by pacozaa** [comment] 2016-02-16 11:29
I use `angular@1.3.6-beta.1`  and `$state.go('collectionName');` working without `settimeout()`. So I think the issue was fixed.

For people who want to try don't use `meteor update angular@1.3.6-beta.1` it will occur an error, but 
use `meteor remove angular` then `meteor add angular@1.3.6-beta.1`

Thank you.

**Comment by Urigo** [comment] 2016-02-17 22:51
Great.
Angular Meteor 1.3.6 was just released.

**Comment by ThomsC** [comment] 2016-02-18 09:55
Ok..

So I had to rewrite everything in to order to get things work.

I would be nice if you tell everybody somewhere that `$auth.requireUser()`doesn't work anymore. All my problems came because of that.

Could you also show us how to use `this.$awaitUser()` in the resolve cause as far as I know `$scope`can't be use in the resolve so we can't write something like this `$reactive(this).attach($scope);``

Thanks

**Comment by ozsay** [comment] 2016-02-18 10:11
@ThomsC Can you see if the API docs is sufficient ? http://www.angular-meteor.com/api/1.3.6/auth

If not, can you tell us what do you think is missing and we will add it to the docs?

Thanks

**Comment by ThomsC** [comment] 2016-02-18 10:25
Yes I checked it that why I asked an exemple on how to verify the user in the `resolve`part of a route and not in the `controller` as it is demonstrate in the documentation

**Comment by dotansimha** [comment] 2016-02-18 16:01
@ThomsC 
`awaitUser` provides the same functionality as `requireUser`, it returns a promise that resolves when the user is logged in...

Actually it exactly like you used to do it with `requireUser`:
````js
$stateProvider
    .state({
        template: '<my-component></my-component>',
        resolve: {
          user: ($auth) => {
            return $auth.awaitUser();
          }
        }
    });
````

Also, you can implement it your self, like in Socially:
https://github.com/Urigo/meteor-angular-socially/blob/master/client/routes.js#L14-L21

**Closed by dotansimha** 2016-02-18 16:01 UTC
Labels: component: auth, More info needed

**Comment by ThomsC** [comment] 2016-02-18 16:32
@dotansimha 

This code doesn't work :

```javascript

$stateProvider
    .state({
        template: '<my-component></my-component>',
        resolve: {
          user: ($auth) => {
            return $auth.awaitUser();
          }
        }
    });

```

this code works 

```javascript
currentUser: ($q) => {
                        if (Meteor.userId() == null) {
                            return $q.reject('AUTH_REQUIRED');
                        }
                        else {
                            return $q.resolve();
                        }
                    }
```

But I was hopping something like 

```javascript

$stateProvider
    .state({
        template: '<my-component></my-component>',
        resolve: {
          user: ($auth) => {
            return $auth.awaitUser().then((user)=>{
            // do some test on the user
            });
          }
        }
    });

**Comment by Urigo** [comment] 2016-02-22 10:34
Hi everyone and @ThomsC, important note [here](https://github.com/Urigo/angular-meteor/issues/1126#issuecomment-187115397).
