### ISSUE TITLE
debugging souce maps

### ISSUE THREAD

**Issue by mgrivera** [Urigo/angular-meteor#878] opened 2015-11-16 17:10 UTC
Hi all, 

I upgraded angular package to new 1.2 and, as advised in the meteor blog post, remove default ecmascript package, because now angular itself uses babel to transpile javascript code. 

My question is: 

When debugging, I can see the transpiled code in the debugger and not my original javascript code. Why? Evidently, there is something I'm missing here but, what? 

I can see the check-marks for activating the use of *source maps*, when debugging in chrome, are checked. However, when debugging server code, I don't know where this settings are, because I can't see a way of opening a debugging settings page there. 

Can somebody explain how to fix this issue? 

Thanks and bye ...

**Comment by mgrivera** [comment] 2015-11-18 15:18
Hi, well nobody is answering here ... but I'm going to ask again: 

Can I expect the use of source-maps when debugging client (mainly) and server javascript code via Google Chrome? As I said before, I'm removed ecmascript default package when upgraded to angular 1.2. 

Any ideas? 

Thanks and bye ...

**Comment by mgrivera** [comment] 2015-11-26 20:49
Hi all, 

when building my project, I have errors if a add this file (to root folder): 
```javascript
{
    "verbose": false,     // true shows files being compiled
    "debug": true,       // true displays this config file
    "modules": "common",  // what module format Babel should use. See
                          // Babel documentation for "modules" option.
    "blacklist": ['useStrict'],  // Do not change this unless you know
                                 // very well what you are doing.
    "stage": 0,            // see Babel documentation for stage option.
    "extensions": ["js"],    // "js" means compile all ".js" files.
    "sourceMaps": "both"   
}
```
with name **.babelrc** or **babel.json**. 

So I have to remove the file for everything to function properly; off course no source maps are generated or generated correctly, so that chrome can show my original javascript code (ie: es6) when debugging. 

I think I'm close to fixing this issue; however, I can't finally see what changes (in configuration?) I have to do so babel can generate source maps for my code. I don't know where to put and how to write **babelrc** or **babel.json** so source maps are generated correctly. 

Any help is greatly appreciated ... bye

**Comment by mgrivera** [comment] 2015-11-26 21:50
Hi all, 

1. I created a new meteor project, no angular. It includes *ecmascript package* by default. When debugging client code, source maps work; you can see your es6 code in the browser. Perfect! 

2. In my original project (with angular-meteor 1.2.2): 
    * **server code:** *map files* (ie: .js.map) are added for each js file. *sourceMappingURL directive* added at the end of transpiled code. However, when debugging this server code, no source mapping is applied (ie: you see transpiled code in the debugger) 
    * **client code:** *map files* are addedd for each js file. No *sourceMappingURL directive* is added to the end of transpiled code. When debugging, no source mapping is applied. 

What am I missing here? Why normal meteor project (no angular; ecmascript package) applies source maps *out of the box* ?? Why angular (1.2.2) project, with *pbastowski:angular-babel* transpiling with babel, does not?? 

Bye ...

**Comment by pbastowski** [comment] 2015-12-09 20:35
@mgrivera I'm working on this right now.

**Comment by pbastowski** [comment] 2015-12-09 23:54
Ok, I think I have it fixed now, with inline sourcemaps.

Please add angular-bebel explicitly to your project, like this

    meteor add pbastowski:angular-babel@1.0.7

Then restart your Meteor project and let me know if that helped.

**Comment by Urigo** [comment] 2015-12-10 05:00
@mgrivera let me know if that solved your problem and then I'll update the dependency version for the next Angular Meteor version

**Comment by mgrivera** [comment] 2015-12-11 12:27
Wow, happy to have an answer to this issue. I've been waiting for this with lots of interest. 
Sadly, I'm on vacations now (very short vacations). I don't have access to my PC here but we'll return home on next Tuesday. I'll check as soon as I can. 

If another person can answer before my arriving home, it'd be fine ... anyway I'll check on next Tuesday. 

Many thanks for this  and bye ...

**Comment by netanelgilad** [comment] 2015-12-11 14:55
Seems to work for me with the new version..

**Closed** 2015-12-13 18:34 UTC

**Comment by mgrivera** [comment] 2015-12-16 20:26
@pbastowski 

1. I upgraded *pbatowski:angular-babel@1.0.6* to *pbastowski:angular-babel@1.0.7*
2. this is my code (es2015): 
```javascript
let usuarioSeleccionado = {};
```
3. this is what I get in *chrome debugger*: 
```javascript
var usuarioSeleccionado = {};
```
4. Additionally, I receive this warning message in chrome debugger (console): 

>Source map http://localhost:3000/app/client/lib/_app.js?>0d6585d183020e027787ea0ec72877b5c3685c16 points to the files missing from the workspace: [http://localhost:3000/client/lib/_app.js]

Evidently, I'm missing something ... but what? 

Currently, I have *angular@1.2.3*. Do I have to upgrade *angular* package to a newer version? 

Many thanks and bye ...

**Comment by pbastowski** [comment] 2015-12-16 23:56
@mgrivera 
Your angular version is fine, but as you say, evidently something is still not working for you.

We should set up a remote debug session through hangouts, perhaps tomorrow, and then I can have a look at your code to see what is going on in there. How does that sound?

**Comment by mgrivera** [comment] 2015-12-17 17:19
@pbastowski 
Hi, I created a very small repository just for you to check out what is happening to me ... I live in a country (Venezuela) where Internet connection is not good. So I think having a Google hangout won't be a good idea. 

This is what I did: 
1. I created a *new* meteor project 
2. Briefly modified the original meteor code to add a very few es2015 statements 
3. Run the app in the browser and set a breakpoint (debugger) to see the code; while debugging, I could see original (es2015) code. Perfect. This is with *ecmascript* package. 
4. Removed ecmascript and added *pbastowski:angular-babel* (1.0.7). Run the program; when debugging, I saw transpiled code (es5) instead of original code. 
5. Removed *es5-shim*: same as 4 above. 

Please inspect the code in this repository: 
https://github.com/mgrivera/meteor2015.git

Many thanks for your help and bye ...

**Comment by pbastowski** [comment] 2015-12-19 11:22
Thanks for providing a test repo. I cloned it and for me it works as expected. That is, when the debugger statement executes in the browser I actually see the ES6 code, see below:

![image](https://cloud.githubusercontent.com/assets/5649024/11912721/8ec3c902-a64a-11e5-9ec3-5edd14d0fcbe.png)

And here is a screenshot of my `meteor list`

![image](https://cloud.githubusercontent.com/assets/5649024/11912733/dedf0668-a64a-11e5-8593-8098e76992b6.png)

Sometimes when I had strange problems deleting the `.meteor/local` folder and restarting Meteor helped.

I'm sorry, but apparently I can't reproduce the problem you are experiencing.

**Comment by mgrivera** [comment] 2015-12-19 12:42
@pbastowski 
Wow, excellent to see *angular-babel* works as expected. Now I don't know what to check in my case. I can see (suppose) you are on a mac. I'm on Windows. Maybe I have to check my google chrome settings? 
What is strange to me is that, in my case, the same scenario, but using core ecmascript package works perfect  for me. 
Anyway, thanks for your help and bye ...

**Comment by pbastowski** [comment] 2015-12-19 13:11
You make a good point re Mac vs Windows. I have access to a windows machine at the moment, so, I'll try it on windows and see what results I get.

**Comment by pbastowski** [comment] 2015-12-19 19:12
I just tried the same repo under Meteor for Windows 7 and the result was the same - I see the ES6 code, not the transpiled code.

**Comment by mgrivera** [comment] 2015-12-20 18:05
Hi @pbastowski, 

Many thanks for all your help. I will check this a little more tomorrow to see if I find out something. I really want to make this work. I'll keep you informed. Thanks again and bye ...

**Comment by kokokenada** [comment] 2016-01-22 22:35
How did this end up? When I step into package code, it shows the wrong line of code for me.  I've addded pbastowski:angular-babel@1.0.7 but I can't debug.  Is there a work around?  (Also running Windows...)

**Comment by mgrivera** [comment] 2016-01-22 22:55
Hi @kokokenada, 

This is how this issue ended up. Note that this is a work around but worked *really* well for me (from that time to this moment). I don't know if @pbastowski  has released a new version of angular-babel that solved this. In the meantime, just have a look at issue #11 in angular-meteor-babel. This is the link: 

https://github.com/pbastowski/angular-meteor-babel/issues/11

Hope this helps. Bye ...

**Comment by kokokenada** [comment] 2016-01-22 23:45
Thanks very much.  For anybody having the debugging problem, unticking "Enable JavaScript source maps", worked around the problem where the debugger showed the wrong line...

**Comment by gauravdhiman** [comment] 2017-08-14 00:48
I am having an issue in seeing the TS (typescript) code when I use Chrome Remote WebView Debugger to debug code running on Android phone. Its not an issue if I run app on desktop chrome and debug it - at that time sourcemaps are present and I am able to see TS code.

Problem is when I run code in Android phone and debug it using Chrome Remote WebView Debugger. In this case I am always seeing the transplied code, not TS code. Please refer attached screenshot.
![remote-webview-debugging](https://user-images.githubusercontent.com/5612223/29254798-7a4a5672-804f-11e7-839e-4efff774c335.png)
