### ISSUE TITLE
getReactively returns no value in initial run

### ISSUE THREAD

**Issue by mxab** [Urigo/angular-meteor#528] opened 2015-07-20 23:03 UTC
Hi,
if I init a variable with initial default value and then use getReactively in a reactive function the value is not returned

for example
```
vm.lang = 'en';
vm.messages = $scope.$meteorCollection(function () {
        var lang = $scope.getReactively('vm.lang');
        if(!lang){
            console.warn('lang not set', lang);
            lang = 'en';
        }
        return Messages.find({
            lang : lang
        });
    }, false);
```

maybe the reactive function should run after the first digest I guess

**Comment by dszczyt** [comment] 2015-08-10 21:26
+1

**Comment by dszczyt** [comment] 2015-08-12 21:55
It seems to be related to #246

**Comment by netanelgilad** [comment] 2015-09-27 07:56
Hey @mxab ,
What exactly is vm? is it a reference to the controller or the $scope? If I remember correctly $scope.getReactively can only get properties on the $scope...

By looking at the code of getReactively, it doesn't seem like there should be a reason it would return different values on initial or afterwards, cause eventually the function always does `return getValue(self);`

**Comment by mxab** [comment] 2015-09-28 15:46
Hey @netanelgilad,
sorry for the 'incomplete' example it is inside a controller with the __controllerAs__ mechanism and the controller is named 'vm'

**Comment by netanelgilad** [comment] 2015-09-28 16:17
So what your problem is that getReactively only works with properties on the $scope. If the property is on the controller you cannot you $scope.getReactively to get it.
You should put your lang prop on $scope and then use getReactively, like so:
```js
$scope.lang = 'en';
....
$scope.getReactively('lang');
```

**Comment by mxab** [comment] 2015-09-28 18:13
Yes but if you use the controllerAs mechanism the controller will be in the scope.

**Comment by netanelgilad** [comment] 2015-09-28 18:38
You are totally right. I missed that about controllerAs.
So I tried it out and it seemed to work for me.. even if I used it right after initializing the value on the vm. Can your share a reproduction that I may have a look?

**Comment by mxab** [comment] 2015-09-28 19:04
yes I'm also trying to make it reproducible in a test, I have this issue in a controller used via a state from the ui router

**Comment by mxab** [comment] 2015-09-29 09:43
@netanelgilad @Urigo 
I managed to create a test case to show case the behaviour
https://github.com/Urigo/angular-meteor/compare/master...mxab:initial_get_reactively

**Comment by mxab** [comment] 2015-09-29 10:07
ok i just realised that the problem comes from the angular side as __vm__ is not initially set on the scope only after the first digest.

Would it be an idea to run the "reactive aware" functions after the initial digest or within a $timout?

**Comment by netanelgilad** [comment] 2015-09-29 13:46
Are you suggesting running the function in a $timeout inside the creation of reactive aware functions? or the user of those functions would wrap their call with a timeout?
I'm not sure about this, but I think running these functions in a $timeout always, is not a good idea, as that may be counter-intuitive for the user of those functions. But I could be wrong here.. need to think it through.

In your situation, did you eventually use $timeout or something of the like to fix the issue?

**Comment by mxab** [comment] 2015-09-29 14:36
I haven't used it sofar with $timeout, I setup a test which indicates that is would work
https://github.com/mxab/angular-meteor/compare/initial_get_reactively...mxab:initial_get_reactively_timeout

currently in my application I use this workarround
```var lang = $scope.getReactively('vm.lang') || vm.lang;```

**Comment by Urigo** [comment] 2015-12-09 23:02
How does this works for you with the new `helpers` syntax?

**Comment by Urigo** [comment] 2015-12-13 18:32
For 1.3.1 we should make sure it's working fine with the new `$scope.reactiveProps` syntax

**Comment by dohomi** [comment] 2015-12-13 18:37
Hi @Urigo 
the 1.3 version is not fully compatible with 1.2 - we still investigate which change breaks our app. Will get back to this issue asap. Cheers

**Comment by Urigo** [comment] 2015-12-20 02:32
Please check out the new `getReactively` in 1.3.1 version and let me know if that still happens to you

**Comment by hlehmann** [comment] 2015-12-20 17:46
looks like `$scope.getReactively` is defined by `angular-meteor.reactive` instead of `angular-meteor.reactive-scope`.

**Comment by Urigo** [comment] 2015-12-20 22:05
@hlehmann it's defined in both so you would be able to use in both on $scope and both on `this` when using controllerAs syntax (or any other object as context)

**Comment by dotansimha** [comment] 2015-12-25 14:40
I think that https://github.com/Urigo/angular-meteor/commit/926bdbf4691b6904797ee68722dbf2ec5357bf41 also fixes it... @Urigo

**Comment by Urigo** [comment] 2015-12-25 16:00
@mxab Can you check if that's the case?

**Comment by Urigo** [comment] 2015-12-28 10:10
Closing, @mxab please reopen is the problem persists

**Closed by Urigo** 2015-12-28 10:10 UTC
