### ISSUE TITLE
upgrade to Meteor 1.9 fails

### ISSUE THREAD

**Issue by dohomi** [Urigo/angular-meteor#1974] opened 2020-01-12 08:42 UTC
Hello Guys,

I tried to upgrade the Meteor version to 1.9 from 1.8.3 but I receive following error:

```
 While loading package angular-compilers@0.3.4:
   error: Command failed: /Users/.meteor/packages/meteor-tool/.1.9.0.z5r58x.aw8bq++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm
   rebuild --update-binary
   Cannot download "https://github.com/sass/node-sass/releases/download/v4.7.2/darwin-x64-72_binding.node":
```
It seems that an outdated node-sass is requested from the compiler package but I couldn't find a way to fix it. Any idea how to get this up and running? Thanks

**Comment by weini01** [comment] 2020-01-15 17:32
Hello,

I have the same issue. Could you please update the node-sass package.
Thanks.

**Comment by mibto** [comment] 2020-01-16 10:57
Hello @Urigo  :)
I have the same issue.
The problem is, that the package "angular-compilers@0.3.4" includes:
- angular-typescript-compiler@0.3.2 
- angular-html-compiler@0.3.2
- angular-scss-compiler@0.3.2

instead of version 0.3.4

**Comment by mrBuchmann** [comment] 2020-03-11 09:49
Hello, 
I've got the same issue. Please approve #1975

**Comment by isibz** [comment] 2020-03-11 11:13
Hello,
I've got the same problem. Please update the package 
The URL https://github.com/sass/node-sass/releases/download/v4.7.2/linux-x64-72_binding.node doesn't exist

Thanks,

**Comment by fidelsam1992** [comment] 2020-03-13 13:01
Same issue, please approve PR #1975

**Comment by bouchepat** [comment] 2020-03-24 20:14
Any update on this? And is this repo even maintained? Thx

**Comment by simontbates** [comment] 2020-03-27 15:12
Same issue. Is there an update on this?

**Comment by danielruiz7** [comment] 2020-03-27 15:23
I posted this issue at meteor forums two days ago... no answer there either

**Comment by AlexAlbala** [comment] 2020-05-01 16:06
Same issue here...

**Comment by AlexSterk** [comment] 2020-05-08 09:34
Here is the (temporary) fix: https://github.com/meteor/meteor/issues/10867#issuecomment-575157740

take the angular-compilers folder from this repo, copy it to packages folder (if you don't have one create one), change the versions to 0.3.4 and run meteor add angular-compilers.

This fixed it for me.

It would be better if this got fixed though @ardatan

**Comment by vicnala** [comment] 2020-06-03 08:12
Same here...

**Comment by vicnala** [comment] 2020-06-03 08:31
> Here is the (temporary) fix: [meteor/meteor#10867 (comment)](https://github.com/meteor/meteor/issues/10867#issuecomment-575157740)
> 
> take the angular-compilers folder from this repo, copy it to packages folder (if you don't have one create one), change the versions to 0.3.4 and run meteor add angular-compilers
> 
> This fixed it for me.
> 
> It would be better if this got fixed though @ardatan

This works for meteor up to 1.10.2

**Comment by danielruiz7** [comment] 2020-11-17 18:46
Hello guys,

I followed the workaround and I also was able to upgrade to meteor 1.11.1 but.....

Lazy module loading stopped working... I managed to make it work doing the following (in case anyone need it):

- Copy 'angular-typescript-compilers' to my packages folder.
- Replace 'replaceDynamicLoadingCode' function with this:

`
replaceDynamicLoadingCode = function (code) {

    while (code.match(LOAD_CHILDREN_REGEX) && code.match(LOAD_CHILDREN_REGEX).length > 0) {

      code = code.replace(LOAD_CHILDREN_REGEX,
        (url, match) => {
          url = url.split('loadChildren:').join('').split(' ').join('').split('\'').join('').split('"').join('').split(',').join('');
          const urlArr = url.split('#');
          let modulePath = urlArr[0].trim();
          let moduleName = urlArr[1].trim();
          if (this.isAot) {
            modulePath += '.ngfactory';
            moduleName += 'NgFactory';
          }
          return `loadChildren: () => module.dynamicImport('${modulePath}').then(allModule => allModule['${moduleName}'])`;
        });

    }

    return code;
  }
`

- Run meteor add angular-typescript-compiler


Regards!

**Comment by danielruiz7** [comment] 2020-11-17 19:20
Well, AOT stopped working also... sadly my knowledge of the packages isn't enough to fix it.

This is the error: 

`Uncaught Error: Invalid configuration of route '': routes must have either a path or a matcher specified
    at validateNode (router.ngfactory.ts:38)
    at validateConfig (router.ngfactory.ts:38)
    at validateNode (router.ngfactory.ts:38)
    at validateConfig (router.ngfactory.ts:38)
    at Router.resetConfig (router.ngfactory.ts:38)
    at new Router (router.ngfactory.ts:38)
    at setupRouter (router.ngfactory.ts:38)
    at _callFactory (router.ngfactory.ts:38)
    at _createProviderInstance (router.ngfactory.ts:38)
    at initNgModule (router.ngfactory.ts:38)`

Can someone help?

Thanks

**Comment by ardatan** [comment] 2021-03-04 01:35
Does it work right now with version 0.4.0?

**Comment by danielruiz7** [comment] 2021-03-05 10:35
@ardatan Upgrading now works with version 0.4.0 thank you!

But I am facing the same problems with LazyLoading as before when I managed to upgrade using local packages.

The message I get is "app-routing.module ignored due to some errors!" This routing module has a couple paths with "loadChildren: 'pathToModule/moduleName.module#ModuleName", previously I had to change "replaceDynamicLoadingCode" function from angular-typescript-compiler to support it, in the way it is implemented it seems to only support one 'loadChildren' per file.

**Comment by ardatan** [comment] 2021-03-05 10:41
I think lazy loading syntax has been changed;
`loadChildren: () => import('./items/items.module').then(m => m.ItemsModule)`

**Comment by danielruiz7** [comment] 2021-03-05 11:28
Still using angular < 8

Which angular version is recommended to use with angular-compilers?

**Comment by ardatan** [comment] 2021-03-05 14:10
It should work with all LTS versions. Closing this issue. You can create a new issue if you have problems with new version.

**Closed by ardatan** 2021-03-05 14:10 UTC
