### ISSUE TITLE
Array item updated in client is shown as null in server

### ISSUE THREAD

**Issue by JohnAReid** [Urigo/angular-meteor#763] opened 2015-10-15 19:15 UTC
This is really strange, I m just doing a quick and dirty display/update of static data stored on the server. The main table is loaded on the client using $meteor.subscribe and $meteor.collection just as the$meteor.subscribe / $scope.$meteorSubscribe API example.
The data is bit difiicult to follow but an example is:

{
    "_id" : "vets1",
    "description" : "animal vets test",
    "level" : 2,
    "arr" : [ 
        {   "id" : 0,  }, 
        {   "id" : 1,   "file" : 5,  "key" : [  4,  5  ] },
], ..........

Most of the data is being changed by input elements in the dom and all is fine but the array for  "key" : [  4,  5  ] is being changed by the controller. 
Adding to the array  "key" : [  4,  5  ] works fine - but when items are spliced from the array it replaces the item with null i.e.  "key" : [  4,  null  ]  - but ony on the server - the client is showing the correct value of  "key" : [  4  ] . 
I update the key by calculating the new array as a temp varaible and the setting the key value to the temp varaible - but even using a hard coded example of arr.Key = [4] ; the server would show "key" : [  4,  null  ]  (assuming there were two items in the aeeay before the edit).

**Comment by rgnevashev** [comment] 2015-10-21 11:27
confirm +
My doc looks http://clip2net.com/s/3paq7v0 after i delete images.$
modifier = {$unset:{'images.2':true}}

**Comment by netanelgilad** [comment] 2015-10-24 06:35
Hey @JohnAReid , @rgnevashev ,
What version of meteor and angular package are you using? There was an issue with this in meteor prior 1.2.0.2 and also in the angular package.
If you can,  share your code so I can take a look and see what the problem is.
Thanks.

**Comment by JohnAReid** [comment] 2015-10-24 09:00
If i run meteor update I get:  "This project is already at Meteor 1.2.0.2, the latest release."
but if I look in the folder versions under .meteor I it says  meteor@1.1.9 and angular@1.0.1
angular:angular@1.4.7

**Comment by JohnAReid** [comment] 2015-10-24 10:21
I have put a version on the meteor deploy site: http://angularnullarray.meteor.com

Do you want the source  - if so where?

**Comment by netanelgilad** [comment] 2015-10-24 10:26
So the fix for splicing arrays in angular-meteor landed in 1.0.2 as you can see here: https://github.com/Urigo/angular-meteor/releases/tag/1.0.2. By your version file, you are using 1.0.1. try updating angular: `meteor update angular`, and see if that helps.
If that doesn't work, then please the source and i'll have a look (deployed versions are minified and uglified so not much help there)

**Comment by JohnAReid** [comment] 2015-10-24 10:43
Confused about the version issue as the test package was created new less than a hour ago - so it should have been up to date. Did meteor update angular - but no difference.

Link to source here; http://1drv.ms/1GxLN5U

**Comment by Urigo** [comment] 2015-11-02 13:41
Fixed in 1.0.4

**Closed by Urigo** 2015-11-02 13:41 UTC

**Comment by MarkPhillips7** [comment] 2015-11-08 00:23
I actually just encountered this issue using 1.0.7. I noticed that the problem only sometimes occurs. I suspect that the problem is due to $unset and $pull updates being executed in parallel. If $unset executes before $pull it works (null entries are removed from the subarray), but if $pull executes first it has no null entries to remove since they have not been $unset yet.

**Comment by MarkPhillips7** [comment] 2015-11-08 01:27
After further investigation my problem was actually caused by the same mongo error from #793. I'll add a comment over there.

**Comment by DAB0mB** [comment] 2015-11-08 21:38
@MarkPhillips7 It's wierd that the $pull operation is performed before the $unset operations, because we have a mongo modifer builder called `getUpdates` which takes to objects as arguments and finds the diffrences between them, and then it produces an update object out of it. Take a look at [this](https://github.com/Urigo/angular-meteor/blob/master/packages/angular-meteor-data/lib/get-updates.js#L151) line, as you can see, the $pull modifier is created after $unset. So how come the $unset is performed before the $pull? Can you show an example of your scenario?

**Comment by DAB0mB** [comment] 2015-11-08 21:40
Just to make it clear the update operations are performed parallely by their order in the `updates` object.

**Comment by MarkPhillips7** [comment] 2015-11-08 22:03
@DAB0mB My suspicion was wrong. The $unset indeed was performed before the $pull. The real cause of my issue was that the $pull contained an array as well as an array nested within the first array,which caused a mongo exception. I added details at #793.

**Comment by DAB0mB** [comment] 2015-11-09 20:06
@MarkPhillips7 can you please try this version: https://github.com/DAB0mB/angular-meteor/tree/v1.0.x
and tell me if it works for you? Make sure you use branch v1.0.x

**Comment by MarkPhillips7** [comment] 2015-11-10 13:49
@DAB0mB Branch v1.0.x did 6 the issue for me. Thanks!

**Comment by Urigo** [comment] 2015-11-10 22:06
Released in `angular@1.0.8` and will soon be release in `angular@1.2.1`

**Comment by activeperception** [comment] 2015-12-15 17:20
Hi, 

I just found out that my project (latest meteor@1.2.1 and angular-meteor@1.3.0) is effected by this bug too.

I add / remove an object to a subarray of a $meteor.object on ng-change and clicking rapidly the checkbox causes this exact issue (the remove sets the element to Null instead of stripping it from the DB).

I'll try to put together a toy project, see if I can replicate the problem, and post the link here.

/Raffaele
