### ISSUE TITLE
Reference FS.File directly to an object

### ISSUE THREAD

**Issue by snowping** [Urigo/angular-meteor#865] opened 2015-11-12 18:47 UTC
Dear community,

I am a beginner with meteor and angular meteor, but it has been a pleasure to work with so far. So maybe my following issue is an obvious one. When I try to reference a FS.File directly to a property of an object as I read in the API documentation here: https://github.com/CollectionFS/Meteor-CollectionFS, I get an error saying ""TypeError: Cannot convert undefined or null to object". 

After installing the additional package cfs:ejson-file I tried something like:
```javascript
vm.images.save(vm.newProfileImage).then(function (result) {
                    var imageFS = result[0]._id;
                    vm.contact.profileImage = imageFS;
                });
```
instead of saving only the ID of the FS.File (like in Tutorial)
```javascript
vm.images.save(vm.newProfileImage).then(function (result) {
                    var imageFS = result[0]._id;
                    vm.contact.profileImage = imageFS._id;
                });
```
Am I missing something? I am using the newest angular 1.2.1 package.

Thanks, Joël

**Comment by triniwiz** [comment] 2015-11-14 02:14
if your still using the autopublish package you should be able to do something like this

```js
$scope.profileImage = scope.$meteorObject(Images, {_id:result[0]._id })
```
and in the template get the image with
```html
<img ng-src={{profileImage.url()}}>
```

**Comment by snowping** [comment] 2015-11-17 06:00
Thanks for your answer, I thought there is another way to get the actual image without going through the images collection.

**Comment by snowping** [comment] 2016-01-05 10:19
Thanks @Urigo 

I tried it with the new API and it seems working but I get a "Maximum call stack size exceeded" error when I'm working with direct image references (e.g. specific image per model).

Now with new API saving an image reference directly works as expected:
```
var newImage = new FS.File(vm.newProfileImage);
            newImage.metadata = {owner: contactId};
            var imageRef = Images.insert(newImage, function(error, imageId) {
                if (error) {
                    logger.error(error.toString(), error, 'Error');
                } else {
                    logger.log('image inserted successful: ' + imageId);
                }
            });

vm.contact.profileImage = imageRef;
```
loading image url in view is working but I got the "Maximum call stack size exceeded", also with one time binding option. 
```
<img ng-src="{{vm.contact.profileImage.url()}}" alt="profile image">
```
or using one time binding
```
<img ng-src="{{::vm.contact.profileImage.url()}}" alt="profile image">
```

Furthermore within controller functions the same error happens when I call either vm.contact.profileImage.getFileRecord() or .url().

**Comment by cranesandcaff** [comment] 2016-01-06 02:35
Also getting the maximum call stack size exceeded error.

**Comment by cranesandcaff** [comment] 2016-01-06 03:03
I believe the issue is that we're calling a function inside of the template `img.url()` which gets called every time the digest loop runs through. 

This is my rough workaround for the issue, inside of a helper.

    var profileImages = ProfileImages.find().fetch()
    this.imgs = profileImages.map(img => img.url())

   

This kind of works. It's not reactive or anything though.

**Comment by snowping** [comment] 2016-01-06 13:18
Ok, so your are saying since version 1.3.2 you haven't got the issue anymore? I am using version 1.3.4 and still having the issue. My situation is probably slightly different to your as I am using it without a separate image collection.  

Thanks for your workaround. I could workaround my situation as follows:

````
        vm.helpers({
            contact: function() {
                return Contacts.findOne({_id: $stateParams.contactId });
            },
            profileImageUrl: function() {
                var contact = Contacts.findOne({_id: $stateParams.contactId });
                return contact.profileImage.url();
            }
        });
```
instead of:
```
        vm.helpers({
            contact: function() {
                return Contacts.findOne({_id: $stateParams.contactId });
            }
        });

        var profileImageUrl = vm.contact.profileImage.url(); 
```

**Comment by cranesandcaff** [comment] 2016-01-06 15:16
Woah, woah, woah, you can add file objects to a collection? 

I'm calling the url method within the template. 

Did the workaround work for you? 

Yeah, I locked my version a 1.3.2 and I don't get the infinite watchers bug when calling `.url()` within a template. I would recommend adding a check for the subscription completion so that it doesn't throw a reference error.

**Comment by snowping** [comment] 2016-01-06 15:28
Yes, indeed. You'll find the official documentation here: https://github.com/CollectionFS/Meteor-CollectionFS#storing-fsfile-references-in-your-objects. In order to get this to work you need to add an additional package: cfs:ejson-file

yeah for the sake of simplicity I did put the line directly under helpers here but yes you are right in my real controller I had put it after subscription is ready and vm.contact is fully loaded.

the workaround works great so far, for objects in collection without profileImage I modified it slightly:
````
            profileImageUrl: function() {
                var contact = Contacts.findOne({_id: $stateParams.contactId });
                return contact.profileImage ? contact.profileImage.url() : undefined;
            },
````

**Comment by dotansimha** [comment] 2016-01-06 18:16
@cranesandcaff so everything works as you need? can I close this issue?

Thanks.

**Comment by cranesandcaff** [comment] 2016-01-06 19:08
Good on my end.

**Closed** 2016-01-06 19:25 UTC
