### ISSUE TITLE
Meteor run freezes/hangs during build process

### ISSUE THREAD

**Issue by lukavent** [Urigo/angular-meteor#262] opened 2015-03-25 13:48 UTC
Since the latest meteor updates the app freezes on starting process:
"Building the application /"

My Setup

I'm on Meteor 1.0.4.1 with cordova (android only).
Ubuntu 14.04.1 LTS
Vagrant Box with 32bit: Linux ionic-android 3.13.0-34-generic #60-Ubuntu SMP Wed Aug 13 15:49:09 UTC 2014 i686 i686 i686 GNU/Linux
The / is even not spinning anymore.

I've tested / checked:
1. Deleting .meteor/local/ folder
2. Killing meteor with "kill -9 ps ax | grep node | grep meteor | awk '{print $1}'" stops meteor and it's restartable again without any error message. That means, it doesn't seem to be something with the system itself.
3. Updated NodeJS to v0.10.37
4. Tryed meteor --verbose --raw-logs 
5. Found nothing Logs: syslog
6. Removing all plugins and adding them again for reinstalling them.
7. Removing one plugin by another.
Result was, that it seems to be some kind of issue within build process combined with urigo:angular Plugin. But maybe the build process is simply stopped, because without that plugin errors are thrown, because meteor don't knows how to parse the angular template files.

I've no clue how to get some more detailed informations what and why it's breaking.
I couldn't find any error message.
Any ideas what to check now?

**Comment by Urigo** [comment] 2015-03-25 14:00
Can you please share a reproduction?  
have you made sure all your files are aligned with the latest breaking changes?
1. Files should end with .ng.html and not .tpl  ?
2. Changed that also in the router?

**Comment by lukavent** [comment] 2015-03-26 16:09
Yes, all tpl files, router etc were renamed.
The curious point is, that I'm not getting any kind of an error message.
The build processes simply hangs.

My main problem is, that I simply don't know where I could find some further logs or how I could activate them for more details in the build process.
"meteor --verbose --raw-logs " doesn't helps here.

If you have a clue how to get more logs, this would help.

**Comment by smoke** [comment] 2015-03-26 16:14
I had similar issue running meteor on nitrous.io platform, it was all due to extremely limited resources for the free account I was using.
So when I started meteor it runs mongo, which ate all the free space.

My suggestion would be - try and run meteor on different machine with enough resources (Disk space, RAM, CPU). If it runs it would give you clues what the next steps should be.

Just note that if there is not enough space - no logs could be written.

**Comment by lukavent** [comment] 2015-03-26 19:58
It's on my local development machine. I've on that machine other meteor-angular (with older versions) running without any problems.
The point is: Everything worked well, before I updated.

Here's a bit of the gdb analysis from the broken process:
Reading symbols from /home/vagrant/.meteor/packages/meteor-tool/.1.0.45.11j6g72++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/lib/node_modules/sqlite3/lib/binding/node-v11-linux-ia32/node_sqlite3.node...(no debugging symbols found)...done.
Loaded symbols for /home/vagrant/.meteor/packages/meteor-tool/.1.0.45.11j6g72++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/lib/node_modules/sqlite3/lib/binding/node-v11-linux-ia32/node_sqlite3.node
Reading symbols from /lib/i386-linux-gnu/libnss_files.so.2...Reading symbols from /usr/lib/debug//lib/i386-linux-gnu/libnss_files-2.19.so...done.
done.
Loaded symbols for /lib/i386-linux-gnu/libnss_files.so.2
Reading symbols from /lib/i386-linux-gnu/libnss_myhostname.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib/i386-linux-gnu/libnss_myhostname.so.2
Reading symbols from /lib/i386-linux-gnu/libnss_dns.so.2...Reading symbols from /usr/lib/debug//lib/i386-linux-gnu/libnss_dns-2.19.so...done.
done.
Loaded symbols for /lib/i386-linux-gnu/libnss_dns.so.2
Reading symbols from /lib/i386-linux-gnu/libresolv.so.2...Reading symbols from /usr/lib/debug//lib/i386-linux-gnu/libresolv-2.19.so...done.
done.
Loaded symbols for /lib/i386-linux-gnu/libresolv.so.2
0x55c3fda9 in ?? ()

**Comment by smoke** [comment] 2015-03-26 21:57
@lukavent try using `strace meteor ....` and share the output, it would be contain better information, I hope.

**Comment by Urigo** [comment] 2015-03-27 19:08
can share the code?
also, it the Meteor version itself different?

**Comment by Urigo** [comment] 2015-04-01 16:51
@lukavent please share a reproduction or more information, otherwise I will have to close this issue

**Comment by lukavent** [comment] 2015-04-02 14:22
Sorry, we tried to create something public for reproducing the problem; but that wasn't easy - until we found the reason for that bug.

The trigger for the problem was a simple error in html (not closed html tag) in one of the pages. We somehow did not have seen that. Okay, it's some kind of a stupid bug.

But nevertheless due to simple missing closing html tag it should not result in such a strange behavior. I'm not sure where the main bug is coming from: MeteorAngular-Package, Meteor or NodeJS itself? 

So, what's next?

**Comment by Urigo** [comment] 2015-04-09 16:35
Fixed on 0.8.3

**Closed by Urigo** 2015-04-09 16:35 UTC

**Comment by luisreyes** [comment] 2015-09-24 19:36
**This issue seems to have come back with 1.2**
I cannot have a large JS library file outside the public folder.
for example I had a *kendo.all.min.js* file in `client/lib/scripts` --> App wouldn't build.

**Solution**: move the file to the public folder `public/scripts` and referenced it in the head with a `script` tag 

In previous meteor versions I was allowed to include large lib files in the client folder to be compiled with the rest of the app.

**Comment by Urigo** [comment] 2015-09-25 21:33
@luisreyes can you share a reproduction?
it might be related to loading order?

**Comment by AlexeyMK** [comment] 2015-10-09 05:05
Can confirm I'm experiencing this issue with 1.2.  With me, removing a giant vendor JS file (https://atmospherejs.com/gnomathibus/meteor-phaser) fixed the problem.  

Reinstalling Meteor didn't help. Removing .meteor/local didn't help. My coding partner didn't have this problem (we're both on OS X, I'm on 10.9 and he's on 10.10).

**Comment by batm4n** [comment] 2015-10-16 11:15
Confirmed on same issue, hangs on `Building the application                  \` when large library added.

**Comment by juniobranco** [comment] 2015-10-25 06:08
+1 Same issue

**Comment by dagvonkr** [comment] 2015-10-26 12:50
+2 Same issue, and node is constantly using 100% ++ of my CPU and computer is getting hot!

**Comment by pvmeijel** [comment] 2015-10-30 13:38
+1 I have the same issue with the (quite big) Kendo UI library.

**Comment by netanelgilad** [comment] 2015-10-31 09:14
Hey guys, has anyone tried putting their large files inside a clean meteor project and see if the problem still occurs? This may be a meteor issue and not angular-meteor...

**Comment by juniobranco** [comment] 2015-10-31 09:18
I have done it without angular-meteor and you are right seems to be an
issue with Meteor itself

**Comment by LuchoPipe** [comment] 2015-12-10 15:27
The solution posted by luisreyes works for me!

**Comment by Koda1004** [comment] 2015-12-18 14:26
Same issue with the viz.js library. Ideally I want this code to run on the server, and I don't think the solution of putting it in /public works with that.

**Comment by Urigo** [comment] 2015-12-19 02:16
@Koda1004 looks like this is a Meteor issue, there is a new thread on the Meteor forums to help us test build times on the new Meteor 1.3 beta, please review and comment there:
https://forums.meteor.com/t/help-us-test-build-times-in-meteor-1-3/15031

**Comment by bernardnahas** [comment] 2016-03-01 10:01
I had an unrelated issue with similar symptoms (1.2). Sharing my fix in case it helps any new meteor users. My build would hang and node would take 100% CPU. Needed kill -9 to stop it.
My problem was that I 'bundled' the output .tar.gz into my project directory, then un-tared it out of curiosity but forgot to delete it -- oops. With the untared bundle there, 'meteor run' would hang. Fixed by deleting the bundle/ directory.

**Comment by apuravchauhan** [comment] 2016-04-19 14:48
@bernardnahas  worked for me as well.

**Comment by bachly** [comment] 2016-05-28 10:33
Removing large JS files works for me.

**Comment by harvitronix** [comment] 2017-02-12 21:53
I had the same issue, and it was because I was sym linking a folder in my `/public` folder that had tens of thousands of files in it.

Removing the sym link fixed the problem for me. Hope this helps others!
