### ISSUE TITLE
TypeError: idStringify is not a function

### ISSUE THREAD

**Issue by nigel-dewar** [Urigo/angular-meteor#701] opened 2015-09-22 23:44 UTC
Hi Following through your tutorial, getting this error 
at angular_angular.js:12458 TypeError: idStringify is not a function whilst following through your awesome tut for socially. I did this tutorial a few months ago and had no issues, so I assume Im getting this error because something has changed in meteor ( v1.2) that does not work with your package. My assumption anyway. here is the addtional output I get, 

at http://localhost:3000/packages/urigo_angular.js?afe8984e5688748b37dc02d2f183ac165b948269:391:12
    at Array.forEach (native)
    at Function._.each._.forEach (http://localhost:3000/packages/underscore.js?46eaedbdeb6e71c82af1b16f51c7da4127d6f285:149:11)
    at diffArray (http://localhost:3000/packages/urigo_angular.js?afe8984e5688748b37dc02d2f183ac165b948269:389:5)
    at updateCollection (http://localhost:3000/packages/urigo_angular.js?afe8984e5688748b37dc02d2f183ac165b948269:1352:3)
    at http://localhost:3000/packages/urigo_angular.js?afe8984e5688748b37dc02d2f183ac165b948269:1178:11
    at http://localhost:3000/packages/angular_angular.js?feeaf4750c9fd3ceafa9f712f99a21ee6fef9b41:17819:31
    at completeOutstandingRequest (http://localhost:3000/packages/angular_angular.js?feeaf4750c9fd3ceafa9f712f99a21ee6fef9b41:5529:10)
    at http://localhost:3000/packages/angular_angular.js?feeaf4750c9fd3ceafa9f712f99a21ee6fef9b41:5806:7

Im a this level through your tuts
http://angular-meteor.com/tutorials/angular1/adding-removing-objects-and-angular-event-handling

cheers

**Comment by ruslanchek** [comment] 2015-09-23 07:56
Have the same issue. I think it's because of some incompatibility with new Meteor 1.2.x.

**Comment by nigel-dewar** [comment] 2015-09-23 08:08
I rekon ur right there bro. I was trying to figure out how to download and run older version.


Sent from Samsung Mobile

<div>-------- Original message --------</div><div>From: Ruslan Shashkov <notifications@github.com> </div><div>Date:23/09/2015  15:56  (GMT+08:00) </div><div>To: Urigo/angular-meteor <angular-meteor@noreply.github.com> </div><div>Cc: nigel-dewar <nigeldewar@live.com> </div><div>Subject: Re: [angular-meteor] TypeError: idStringify is not a function (#701) </div><div>
</div>
Have the same issue. I think it's because of some incompatibility with new Meteor 1.2.x.

---

**Comment by h4de5** [comment] 2015-09-23 14:46
i had the same error on the angular example app on meteor.com.  updating your package helped:
```
meteor add urigo:angular@0.10.2
```
helped.

**Comment by BrianLichliter** [comment] 2015-09-23 20:52
I tried the same solution as @h4de5 but it created a new one for me.

I ended up getting this error when following both the https://www.meteor.com/tutorials/angular/creating-an-app tutorial and the http://angular-meteor.com/tutorials/angular1/bootstrapping tutorial.

ReferenceError: check is not defined
    at Array.AngularMeteorCollection.remove (angular.js:662)
    at Array.AngularMeteorCollection._saveChanges (angular.js:836)
    at Object.fn (angular.js:812)
    at Scope.$digest (angular_angular.js:15767)
    at Scope.$apply (angular_angular.js:16038)
    at HTMLButtonElement.<anonymous> (angular_angular.js:23494)
    at HTMLButtonElement.jQuery.event.dispatch (jquery.js:4665)
    at HTMLButtonElement.elemData.handle (jquery.js:4333)(anonymous function) @ angular_angular.js:12458(anonymous function) @ angular_angular.js:9245Scope.$digest @ angular_angular.js:15785Scope.$apply @ angular_angular.js:16038(anonymous function) @ angular_angular.js:23494jQuery.event.dispatch @ jquery.js:4665elemData.handle @ jquery.js:4333

**Comment by nigel-dewar** [comment] 2015-09-23 21:11
I'd like to think meteor would be useful one day.

Sent from Samsung Mobile

<div>-------- Original message --------</div><div>From: Brian Lichliter <notifications@github.com> </div><div>Date:24/09/2015  04:52  (GMT+08:00) </div><div>To: Urigo/angular-meteor <angular-meteor@noreply.github.com> </div><div>Cc: nigel-dewar <nigeldewar@live.com> </div><div>Subject: Re: [angular-meteor] TypeError: idStringify is not a function (#701) </div><div>
</div>
I tried the same solution as @h4de5 but it created a new one for me.

I ended up getting this error when following both the https://www.meteor.com/tutorials/angular/creating-an-app tutorial and the http://angular-meteor.com/tutorials/angular1/bootstrapping tutorial.

ReferenceError: check is not defined
    at Array.AngularMeteorCollection.remove (angular.js:662)
    at Array.AngularMeteorCollection._saveChanges (angular.js:836)
    at Object.fn (angular.js:812)
    at Scope.$digest (angular_angular.js:15767)
    at Scope.$apply (angular_angular.js:16038)
    at HTMLButtonElement.<anonymous> (angular_angular.js:23494)
    at HTMLButtonElement.jQuery.event.dispatch (jquery.js:4665)
    at HTMLButtonElement.elemData.handle (jquery.js:4333)(anonymous function) @ angular_angular.js:12458(anonymous function) @ angular_angular.js:9245Scope.$digest @ angular_angular.js:15785Scope.$apply @ angular_angular.js:16038(anonymous function) @ angular_angular.js:23494jQuery.event.dispatch @ jquery.js:4665elemData.handle @ jquery.js:4333

---

**Comment by ruslanchek** [comment] 2015-09-23 21:17
I'll remove urigo:angular, and then just install a official angular package (meteor add angular). That will help!

**Comment by BrianLichliter** [comment] 2015-09-23 23:08
@ruslanchek I did that too but it didnt help :( maybe ill make a separate issue for my "check is not defined bug"

**Comment by nigel-dewar** [comment] 2015-09-24 02:14
Thanks this worked a treat!!! :)

**Comment by Svenskunganka** [comment] 2015-09-24 07:46
@BrianLichliter you gotta install the `check` package: `meteor add check`

**Comment by Urigo** [comment] 2015-09-24 10:33
Hi everyone and sorry for that bug.
I've fixed it now and released a new version `angular@1.0.0-rc.7`
Please test it out with the latest Meteor and let me know if that helped

**Comment by Svenskunganka** [comment] 2015-09-25 00:18
@Urigo awesome work as always! Just switched from `angular-meteor` to `angular@1.0.0-rc.7`. Really happy to see your work officially supported by Meteor.

**Comment by nigel-dewar** [comment] 2015-09-25 03:10
Thanks Uri, it works PERFECT!!!!!!!!! 

 

Cheers SOOO MUCH!

**Comment by Urigo** [comment] 2015-09-25 19:09
Fixed in `1.0.0-rc.10`

**Closed by Urigo** 2015-09-25 19:09 UTC

**Comment by nikunjchapadia** [comment] 2015-09-27 19:22
Verified your fix (version 1.0.0-rc.11), it works for me thanks.
meteor remove urigo:angular
meteor add angular

**Comment by alecperkey** [comment] 2015-10-12 00:33
this same error is happening with angular 1.0.2 (latest)
I am able to continue the angular-meteor tutorial at http://angular-meteor.com/tutorials/angular1/search-sort-pagination-and-reactive-vars by downgrading

meteor remove angular
meteor add angular@=1.0.0-rc.10

Thanks for teaching me so much Uri!

**Comment by Urigo** [comment] 2015-10-12 00:48
@alecperkey can you share a reproduction?
I will look on it
thanks

**Comment by alecperkey** [comment] 2015-10-12 14:57
@Urigo I couldn't reproduce it this morning with the zip from step 10. I may have just made a mistake in the tutorial.
