### ISSUE TITLE
(Windows) Package angular-compilers error "Javascript heap out of memory" with meteor 1.6, angular 4

### ISSUE THREAD

**Issue by bouchepat** [Urigo/angular-meteor#1728] opened 2017-11-02 16:46 UTC
Hi,

I'm trying the new angular-compilers package, but can only use with meteor 1.5.2.2 (since 1.6 does not work properly on Windows), unfortunately I'm getting the following error:

Is there something I'm missing or this package cannot be used with <1.6 version?
Thanks.

```

   While loading plugin Angular Compilers from package  angular-compilers:
   vm.js:24:10: Block-scoped declarations (let, const, function, class)
   not yet supported outside strict mode
   at Object.exports.createScript (vm.js:24:10)
   at C:\tools\fs\files.js:1162:34
   at Function.time (C:\tools\tool-env\profile.js:305:10)
   at Object.files.runJavaScript (C:\tools\fs\files.js:1100:18)
   at C:\tools\isobuild\bundler.js:1973:15
   at Array.forEach (native)
   at Function._.each._.forEach
   (C:\Users\Patrick\AppData\Local\.meteor\packages\meteor-tool\1.5.2_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
   at JsImage.load (C:\tools\isobuild\bundler.js:1858:7)
   at C:\tools\isobuild\isopack.js:536:16
   at C:\tools\utils\buildmessage.js:359:18
   at [object Object]._.extend.withValue
   (C:\tools\utils\fiber-helpers.js:89:14)
   at C:\tools\utils\buildmessage.js:352:34
   at [object Object]._.extend.withValue
   (C:\tools\utils\fiber-helpers.js:89:14)
   at C:\tools\utils\buildmessage.js:350:23
   at [object Object]._.extend.withValue
   (C:\tools\utils\fiber-helpers.js:89:14)
   at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
   at C:\tools\isobuild\isopack.js:526:20
   at Function._.each._.forEach
   (C:\Users\Patrick\AppData\Local\.meteor\packages\meteor-tool\1.5.2_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
   at [object Object].ensurePluginsInitialized
   (C:\tools\isobuild\isopack.js:514:7)
   at C:\tools\isobuild\compiler.js:382:16
   at Array.forEach (native)
   at C:\tools\isobuild\compiler.js:381:26
   at C:\tools\utils\buildmessage.js:359:18
   at [object Object]._.extend.withValue
   (C:\tools\utils\fiber-helpers.js:89:14)
   at C:\tools\utils\buildmessage.js:352:34
   at [object Object]._.extend.withValue
   (C:\tools\utils\fiber-helpers.js:89:14)
   at C:\tools\utils\buildmessage.js:350:23
   at [object Object]._.extend.withValue
   (C:\tools\utils\fiber-helpers.js:89:14)
   at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
   at C:\tools\isobuild\compiler.js:377:16
   at C:\tools\isobuild\compiler.js:184:28
   at Object.withCache (C:\tools\fs\files.js:1694:12)
   at C:\tools\isobuild\compiler.js:183:11
   at Array.forEach (native)
   at Function._.each._.forEach
   (C:\Users\Patrick\AppData\Local\.meteor\packages\meteor-tool\1.5.2_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
   at Object.compile (C:\tools\isobuild\compiler.js:178:5)
   at C:\tools\isobuild\bundler.js:2956:24
   at C:\tools\utils\buildmessage.js:271:13
   at [object Object]._.extend.withValue
   (C:\tools\utils\fiber-helpers.js:89:14)
   at C:\tools\utils\buildmessage.js:264:29
   at [object Object]._.extend.withValue
   (C:\tools\utils\fiber-helpers.js:89:14)
   at C:\tools\utils\buildmessage.js:262:18
   at [object Object]._.extend.withValue
   (C:\tools\utils\fiber-helpers.js:89:14)
   at C:\tools\utils\buildmessage.js:253:23
   at [object Object]._.extend.withValue
   (C:\tools\utils\fiber-helpers.js:89:14)
   at Object.capture (C:\tools\utils\buildmessage.js:252:19)
   at bundle (C:\tools\isobuild\bundler.js:2899:31)
   at C:\tools\isobuild\bundler.js:2846:32
   at Object.withCache (C:\tools\fs\files.js:1694:12)
   at Object.exports.bundle (C:\tools\isobuild\bundler.js:2846:16)
   at C:\tools\runners\run-app.js:583:36
   at Function.run (C:\tools\tool-env\profile.js:490:12)
   at bundleApp (C:\tools\runners\run-app.js:582:34)
   at [object Object]._.extend._runOnce
   (C:\tools\runners\run-app.js:626:35)
   at [object Object]._.extend._fiber
   (C:\tools\runners\run-app.js:885:28)
   at C:\tools\runners\run-app.js:412:12


=> Your application has errors. Waiting for file change.

```

**Comment by bouchepat** [comment] 2017-11-02 17:35
I managed to install meteor 1.6 and npm install seems to work. When I run the app, this is the new error message:

```
   Building for web.browser                  |
<--- Last few GCs --->

[4256:0085F758]   392380 ms: Mark-sweep 723.0 (806.7) -> 723.0 (806.7) MB, 1299.
1 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, wa
lltime since start of marking 1299 ms) last resort GC in old space requested
[4256:0085F758]   393695 ms: Mark-sweep 723.0 (806.7) -> 723.0 (806.7) MB, 1314.
9 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 303162F9 <JSObject>
    1: /* anonymous */ [C:\Users\Patrick\AppData\Local\.meteor\packages\angular-
compilers\0.2.5\plugin.Angular_Compilers.os\npm\node_modules\meteor\babel-compil
er\node_modules\babel-traverse\lib\index.js:~94] [pc=10096627](this=1DF3AE99 <JS
Function traverse (sfi = 1C3C90B1)>,node=46DE359D <Node map = 09721799>,opts=1ED
55EF1 <Object map = 09753CA9>,scope=52C472B1 <Scope map = 09753BF9>,state=369E0B
CD <...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memo
ry
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! zeteor@1.0.0 prod: `meteor --settings settings.json`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the zeteor@1.0.0 prod script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Patrick\AppData\Roaming\npm-cache\_logs\2017-11-02T17_32_5
1_815Z-debug.log
```

**Comment by ardatan** [comment] 2017-11-02 22:40
Could you reproduce the problem?

**Comment by bouchepat** [comment] 2017-11-03 12:22
I found out the issue was due to some large json files in the private folder (used for data migration). Commenting the line where it parses out the json files solved the problem. There might be a relation with https://github.com/meteor/meteor/issues/9075 . 

However, I was still not able to run the app successfully with 1.6 and the new angular-compilers package; I ran into some runtime exceptions **bad character** in some .js files (sorry don't have the exact trace); this is a new error and I will open a new ticket when I have time to get to it.
By the way, I tried to run the all-in-one example but it did not work for me. Has it been successfully tested on Windows?

Thanks.

**Comment by ardatan** [comment] 2017-11-03 21:53
Actually we need more specific details about issue, like trace etc.

**Comment by bouchepat** [comment] 2017-11-05 22:09
Hello,

I've given another try and got the stack traces requested.
1.  Error: "Javascript heap out of memory":
```
   Building for web.browser                  \
<--- Last few GCs --->

[10784:0000020E7DDE8280]   454493 ms: Mark-sweep 1405.3 (1587.7) -> 1405.2 (1587.7) MB, 2514.9 / 0.1 ms  allocation failure GC in old space requested
[10784:0000020E7DDE8280]   456908 ms: Mark-sweep 1405.2 (1587.7) -> 1405.1 (1540.7) MB, 2414.5 / 0.1 ms  last resort GC in old space requested
[10784:0000020E7DDE8280]   459478 ms: Mark-sweep 1405.1 (1540.7) -> 1405.1 (1540.7) MB, 2569.0 / 0.1 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000002A421725E91 <JSObject>
    1: set [native weak-collection.js:~32] [pc=000002C1B38C18A2](this=000001422769FA81 <JSWeakMap>,key=0000021475D593F1 <Node map = 0000024E42586C99>,value=000002044715C2F9 <JSArray[0]>)
    2: set [C:\Users\bouch\AppData\Local\.meteor\packages\angular-compilers\0.2.8_1\plugin.Angular_Compilers.os\npm\node_modules\meteor\babel-compiler\node_modules\core-js\library\modules\_collection.js:~37] [...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! zeteor@1.0.0 prod: `meteor --settings settings.json`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the zeteor@1.0.0 prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bouch\AppData\Roaming\npm-cache\_logs\2017-11-05T21_24_32_321Z-debug.log

```

As I mentioned in previous post, I'm importing data from json files (in private folder). When I comment the import function I do not receive the error. I think this is related to https://github.com/meteor/meteor/issues/8157.

2. Once commented, I'm getting this error:

```
[client]: ES2015 modules Compilation: 117407.457ms
[client]: TypeScript Files Compilation: 89446.893ms
[server]: ES2015 modules Compilation: 485.351ms
[server]: TypeScript Files Compilation: 19876.034ms
=> Errors prevented startup:

   While processing files with angular-compilers (for target web.browser):
   client/main.scss:1:1: File to import not found or unreadable:
   {}/node_modules/bootstrap/scss/bootstrap.scss.
   Parent style sheet: C:/Repositories/zeteor-web/client/main.scss

=> Your application has errors. Waiting for file change.
```

The file **bootstrap.scss** does exist and is located in **node_modules/bootstrap/scss** folder. This is my main.scss:

```
@import "{}/node_modules/bootstrap/scss/bootstrap.scss";
@import "{}/node_modules/toastr/toastr.scss";
```

3. After I commenting both import, I'm getting this new error:

```
=> Errors prevented startup:

   While building for web.browser:
   client/web/_common/user/login.component.js:52:50: Bad character escape sequence
   (52:50)
   client/web/_common/user/profile.component.js:18:50: Bad character escape
   sequence (18:50)
   client/web/_common/uploaders/dropFile.component.js:54:50: Bad character escape
   sequence (54:50)
   client/web/_common/user/user-buttons.component.js:52:50: Bad character escape
   sequence (52:50)

=> Your application has errors. Waiting for file change.
``` 

Here is the content of **login.component**:

```
import { Component, OnInit } from '@angular/core';
import { UnitOfWork } from '../../../services/unitOfWork';
import * as CONST from '../../../../both/_configurations/constants';
import { GlobalValidator } from '../../../validators/global-validators';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { AuthService } from '../../../services/authorization/auth.service';
import { ILoginVm } from '../../../models/loginVm.interface';

//import template from './login.component.html';
import { Router } from '@angular/router';


@Component({
    templateUrl: './login.component.html',
    styleUrls: ['user.scss']
})

export class LoginComponent implements OnInit {
    loginForm: FormGroup;
    credentials: ILoginVm;
    hasError: boolean = false;
    loggingIn: boolean = false;

    constructor(private _unitOfWork: UnitOfWork, private _formBuilder: FormBuilder, private _authService: AuthService, private _router: Router) { }

    ngOnInit() {
        this._unitOfWork.getSeoService().setSeo({ seoTitle: 'Login', seoDescription: 'Login.', robots: CONST.ROBOT_NONE });

        this.loginForm = this._formBuilder.group({
            username: ['', [Validators.required, GlobalValidator.emailFormat]],
            password: ['', Validators.required]
        });
    }

    onSubmit() {
        if (this.loginForm.valid) {
            this.credentials = {
                username: this.loginForm.value.username,
                password: this.loginForm.value.password
            };
            this.loggingIn = true;
            this._authService.login(this.credentials)
                .then(redirectUrl => {
                    this.hasError = false;
                    this.loggingIn = false;
                    this._router.navigate([redirectUrl]);
                    this._unitOfWork.getNotificationService().successInfo("You are logged in!");
                })
                .catch(err => {
                    this.hasError = true;
                    this.loggingIn = false;
                    this.loginForm.setValue({ username: this.loginForm.value.username, password: '' });
                    this._unitOfWork.getNotificationService().error("Incorrect credentials!");
                });
        }
    }
}
```

I realize there are more than one issue, let me know if you'd like me to create separate issues.
Thanks.

**Comment by ardatan** [comment] 2017-11-06 00:37
About the first problem, I think you have to use different ways to receive that large data, I also agree with that it is about the core of Meteor.
About the second problem, you are trying to import files in a wrong way;
```
@import "bootstrap/scss/bootstrap";
@import "toastr/toastr";
```
So, scss files should be imported without extension, and if they are in node_modules, you should use same syntax with JS module import.
At the last one, I have still need a reproduced issue. ( I think it happens only in Windows)

**Comment by bouchepat** [comment] 2017-11-06 14:37
Thanks, that did fix the issue (2). Is there anything I can do to help debugging issue 3? Was the new compiler package tested on Windows?

Thanks.

**Comment by ardatan** [comment] 2017-11-06 15:26
Your welcome 👍  We are working on this, I think it will be released in a few days.

**Comment by pmcochrane** [comment] 2017-11-24 14:13
I am encountering a similar error for javascript heap out of memory. It's happening when trying to bundle up the meteor app. App is working normally in develop mode and I had it compiling the bundle the other day but it's failing now for an unknown reason. Not really sure where to start but here is the error message produced.

`- Building the ReTIS node app for port 8400...
| (#1) Profiling: ProjectContext prepareProjectForBuild
|  Building local packages                   /
| ProjectContext prepareProjectForBuild                         3,735 ms (1)
|
| Top leaves:
| files.readFile.............................................386 ms (2859)
| files.stat.................................................113 ms (3515)
| files.lstat................................................108 ms (3348)
|
| (#1) Total: 3,735 ms (ProjectContext prepareProjectForBuild)
|

WARNING: The output directory is under your source tree.
         Your generated files may get interpreted as source code!
         Consider building into a different directory instead
         meteor build ../output

[client]: ES2015 modules Compilation: 530.907ms
Creating CodeGenerator!: 5933.762ms
Loading NgModules!: 0.268ms
Generating NgModules!: 13480.151ms
[client]: TypeScript Files Compilation: 52082.195ms
   Linking                                   |
<--- Last few GCs --->

[23738:0x38a09d0]   170212 ms: Mark-sweep 1422.6 (1498.8) -> 1422.5 (1482.8) MB, 1395.2 / 0.1 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 1395 ms) last resort GC in old space requested
[23738:0x38a09d0]   171560 ms: Mark-sweep 1422.5 (1482.8) -> 1422.5 (1482.8) MB, 1347.5 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3874e1425e91 <JSObject>
    1: indexOf(aka ArraySet_indexOf) [/home/paul.cochrane/.meteor/packages/meteor-tool/.1.6.0.d1fvaq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/source-map/lib/array-set.js:~74] [pc=0x17c43537a789](this=0x23c1be5397e9 <ArraySet map = 0x292fd31546e9>,aStr=0x3684b058a181 <String[45]: imports/client/app/app.component.ngfactory.ts>)
    2: _serializeMappin...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/home/paul.cochrane/.meteor/packages/meteor-tool/.1.6.0.d1fvaq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
 2: 0x121809c [/home/paul.cochrane/.meteor/packages/meteor-tool/.1.6.0.d1fvaq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [/home/paul.cochrane/.meteor/packages/meteor-tool/.1.6.0.d1fvaq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/home/paul.cochrane/.meteor/packages/meteor-tool/.1.6.0.d1fvaq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
 5: v8::internal::Factory::NewStruct(v8::internal::InstanceType) [/home/paul.cochrane/.meteor/packages/meteor-tool/.1.6.0.d1fvaq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
 6: v8::internal::Factory::NewTuple3(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [/home/paul.cochrane/.meteor/packages/meteor-tool/.1.6.0.d1fvaq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
 7: v8::internal::LoadIC::LoadFromPrototype(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Smi>) [/home/paul.cochrane/.meteor/packages/meteor-tool/.1.6.0.d1fvaq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
 8: v8::internal::LoadIC::GetMapIndependentHandler(v8::internal::LookupIterator*) [/home/paul.cochrane/.meteor/packages/meteor-tool/.1.6.0.d1fvaq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
 9: v8::internal::IC::ComputeHandler(v8::internal::LookupIterator*) [/home/paul.cochrane/.meteor/packages/meteor-tool/.1.6.0.d1fvaq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
10: v8::internal::LoadIC::UpdateCaches(v8::internal::LookupIterator*) [/home/paul.cochrane/.meteor/packages/meteor-tool/.1.6.0.d1fvaq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
11: v8::internal::LoadIC::Load(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Name>) [/home/paul.cochrane/.meteor/packages/meteor-tool/.1.6.0.d1fvaq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
12: v8::internal::Runtime_LoadIC_Miss(int, v8::internal::Object**, v8::internal::Isolate*) [/home/paul.cochrane/.meteor/packages/meteor-tool/.1.6.0.d1fvaq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
13: 0x17c43510463d
./createDockerImage.bash: line 151: 23738 Aborted                 (core dumped) METEOR_PROFILE=10000 ROOT_URL=${ROOT_URL}:${PORT}/ MAIL_URL=${MAIL_URL} PORT=$port meteor build --debug $dockerFolder/ --directory --architecture os.linux.x86_64 --mobile-settings $settingsFile
`

**Comment by pmcochrane** [comment] 2017-11-24 14:22
For info, I have got my app to bundle by raising the global node memory for meteor. Whilst this works, there is probably still something that needs tweaked in the compilers

export NODE_OPTIONS="--max_old_space_size=4096"

**Comment by ardatan** [comment] 2017-11-25 15:03
It is due to js minifier, so if you disable it, increase the memory or use different minifier, it should work.
It is not `angular-meteor` bug.
https://github.com/meteor/meteor/issues/9075

**Closed by ardatan** 2017-11-25 15:03 UTC
Labels: More info needed

**Comment by Urigo** [comment] 2017-11-27 19:16
we've just released the new `angular-compilers@0.2.9` which suppose to solve this problem.

Please let us know if that is not the case

**Comment by bouchepat** [comment] 2018-02-09 18:22
Problem reoccurs despite NODE_OPTIONS or TOOL_NODE_FLAGS. Issue is on Windows 10, works fine on Windows 7.

```
=> Started proxy.
[client]: HTML Files Compilation: 119.696ms  \
   Building for web.browser                  \
<--- Last few GCs --->

[9816:04337E38]   298690 ms: Mark-sweep 714.4 (805.7) -> 714.4 (797.7) MB, 1109.0 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 1109 ms) last resort GC in old space requested
[9816:04337E38]   299798 ms: Mark-sweep 714.4 (797.7) -> 714.4 (797.7) MB, 1107.7 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 2751632D <JSObject>
    1: /* anonymous */ [C:\Users\bouch\AppData\Local\.meteor\packages\angular-compilers\0.2.9_2\plugin.Angular_Compilers.os\npm\node_modules\meteor\babel-compiler\node_modules\babel-traverse\lib\index.js:~94] [pc=4809DAE7](this=1F294765 <JSFunction traverse (sfi = 35AE1099)>,node=449A776D <Node map = 0737DA49>,opts=28043791 <Object map = 0F5B8FA9>,scope=3707FFBD <Scope map = 0F5B8EF9>,state=46B04101 <...

```

**Comment by bouchepat** [comment] 2018-02-09 18:23
#https://github.com/meteor/meteor/issues/9568

**Comment by pedrofg** [comment] 2018-03-29 13:37
No fix? Meteor running on Windows seems to have a lot of issues.
