### ISSUE TITLE
Unclosed attribute in tag within template stuck the building phase

### ISSUE THREAD

**Issue by Xample** [Urigo/angular-meteor#275] opened 2015-04-06 13:45 UTC
Hi, I just added the following tag
```html
    <a  ng-class="></a>
```
And meteor got completely stuck during the building phase. I had to
```bash
kill -9 pid
```
Normally meteor parses the files and check for possible errors, I did not expected a malformed file.ng.html to be able to crash the building phase this way.

**Comment by netanelgilad** [comment] 2015-04-07 07:47
This seems to be the same case as #262. 
The issue seems to be with html-minifier, that just hangs when there are certain errors in the file it is proccessing. There are multiple issues on this topic at their repo, e.g https://github.com/kangax/html-minifier/issues/213.
If this is really a big problem we just not minify the html files, or we can find the way that meteor parses the html files and maybe do the same before minifying.
@Urigo think you could check that out with the guys at meteor?

**Comment by Xample** [comment] 2015-04-07 08:05
@netanelgilad the problem is that is silently breaks the build processing. Then it's a treasure chase to find which file and line was causing the issue. We should continue minifying the files, what you are pointing is right: the build process bypass the ng.html files validation, then the minifier assuming the files are well formed "crashes". But then if we enable ng.html verification, will the parser comply with the angular's syntax ?

**Comment by netanelgilad** [comment] 2015-04-09 05:44
I tried reproducing this and it didn't hang for me actually. But the fix is still needed and it does help find errors in .ng.html files.
@Xample @lukavent I created a branch for the fix. Can you guys check your code against it?

**Comment by Xample** [comment] 2015-04-09 06:09
Stupid question but how do you test the branch within meteor ? I mean if there is a smart way, because I do not think meteor can install packages directly from a git repository.

**Comment by netanelgilad** [comment] 2015-04-09 06:15
You can git clone this repo to your packages folder. then switch to the branch and remove and re-add urigo:angular (actually i'm not sure if the re-adding is necessary but I do it any way =] )

**Comment by Urigo** [comment] 2015-04-09 16:32
Fixed on 0.8.3

**Closed by Urigo** 2015-04-09 16:32 UTC
