### ISSUE TITLE
sourcemaps not working in 1.3

### ISSUE THREAD

**Issue by mxab** [Urigo/angular-meteor#1327] opened 2016-04-11 15:58 UTC
Hi,
it seems that the sourcemaps are not working anymore.

In this project for example https://github.com/Urigo/meteor-angular-socially.git

It only shows the compiled app.js and the main.js, non of the imports are available
<img width="544" alt="screen shot 2016-04-11 at 17 56 34" src="https://cloud.githubusercontent.com/assets/1607547/14433553/f75175dc-000e-11e6-87e5-736ca39d4e4a.png">

**Comment by mxab** [comment] 2016-04-12 21:29
@pbastowski do you think this is maybe an angular-babel issue?

**Comment by pbastowski** [comment] 2016-04-13 17:52
@mxab I will look into this.

**Comment by pbastowski** [comment] 2016-04-13 18:47
@mxab 
You're right.
So, it would appear that Meteor 1.3 changed something to do with Source Maps and I need to fix my package.
To be continued...

**Comment by mxab** [comment] 2016-04-13 19:10
ok thx, let me know if I should test something

**Comment by pbastowski** [comment] 2016-04-14 20:40
@mxab 
I have spent a couple of hours looking into the issue and trying things, but no luck yet. I think it will take me a few days to find how to do sourcemaps in m13. 

`<whinge warning>`
It's bit of a whinge, I know, but I wish "they" got "their" act together with the core `ecmascript` package and exposed a way for us to add any Babel transformers that we want, like Decorators, for example. Even if Babel no longer wants to support Decorators due to some committee squabbles over the exact details of the implementation.
`</whinge warning>`

**Comment by mxab** [comment] 2016-04-14 21:57
just curious how is everyone else developing angular-meteor applications? not having sourcemaps working takes a bit the fun out or are they working in your projects @pbastowski ?

any ideas/suggestion from @Urigo ?

**Comment by pbastowski** [comment] 2016-04-15 21:18
@mxab 
I've published v1.3.4, which brings back the source maps.
Could you please check if it works also for you?

**Comment by mxab** [comment] 2016-04-15 21:25
Yes Sir, it does so very much! Thank you! :+1:

**Comment by mxab** [comment] 2016-04-26 07:07
@pbastowski it looks like there is still something off in the sourcemaps, while debugging it looks like the breakpoints are one or two lines of

**Comment by pbastowski** [comment] 2016-04-26 08:46
Max, I'm away on vacation for a few days. I'll look into this issue on Sunday or Monday latest.

**Comment by mxab** [comment] 2016-04-26 08:48
No worries, enjoy your vacation :)

**Comment by ebbe-brandstrup** [comment] 2016-05-16 05:21
Any update on this?

I am on angular-meteor 1.3.10 and Meteor 1.3.4 on OS X and my source maps are off by 1 line. Would greatly appreciate a fix for this :)

Thanks!

**Comment by pbastowski** [comment] 2016-05-16 09:23
@ebbe-brandstrup That's a very interesting fix. Does this work for more than one of your transpiled files? If not then let me know and I'll have a look into it.

**Comment by ebbe-brandstrup** [comment] 2016-05-17 05:29
I verified on a colleagues PC today... he had the same issue - breakpoints were off by 1 line in all transpiled files.

For us, the problem was resolved by disabling js source maps in the Chrome dev tools. Then refreshing the page. Then enabling source maps and refreshing again. Now source maps for all transpiled files work correctly. 

We've had the off by 1 issue since we upgraded from Meteor 1.2.x and the latest Angular Meteor version for that to Meteor 1.3.4 and Angular Meteor 1.3.10. 

But now everything is good :)

**Comment by pbastowski** [comment] 2016-05-17 06:43
That's great news. Thank you very much for checking.

**Comment by pbastowski** [comment] 2016-05-17 06:44
@mxab Did you see the solution above? Are you still experiencing problems with your source maps?
Personally, I could not reproduce this problem.

**Comment by mxab** [comment] 2016-05-20 06:12
hmm currently it seems to work for me, strange was that I did the sourcemap on/off thing already once.

**Comment by Urigo** [comment] 2016-05-20 15:42
closing for now but would love to hear others who stumbled on this issue to comment if it works for them

**Comment by ebbe-brandstrup** [comment] 2016-05-30 04:17
Unfortunately, the problem has returned for us now (still on the same versions: Meteor 1.3.4, Angular 1.5.5, Meteor 1.3.10 and pbastowski:angular-babel@1.3.4). 

All transpiled files are off by one again now. And disabling source maps, then refreshing the page and re-enabling source maps no longer makes a difference.

**Comment by mxab** [comment] 2016-05-30 09:32
also experiencing it again, but I cannot really point out when it started

**Comment by ozsay** [comment] 2016-05-30 09:36
@ebbe-brandstrup @mxab , I encountered many issues with sourcemaps on chrome 51. can you see which version of chrome are you using?

**Comment by mxab** [comment] 2016-05-30 09:36
```
Google Chrome	50.0.2661.102 (Official Build) (64-bit)
Revision	c26c0312e940221c424c2730ef72be2c69ac1b67-refs/branch-heads/2661@{#680}
OS	Mac OS X 
Blink	537.36 (@c26c0312e940221c424c2730ef72be2c69ac1b67)
JavaScript	V8 5.0.71.48
```

**Comment by pbastowski** [comment] 2016-05-30 09:39
Well, that's not good.

What versions of Meteor are you guys using?

**Comment by mxab** [comment] 2016-05-30 09:41
METEOR@1.3.2.4

**Comment by pbastowski** [comment] 2016-05-30 14:29
Guys, if you're interested, Meteor 1.3.3-beta.1 allows us to use `.babelrc` to add decorators, etc, thereby removing the need for my `angular-babel` package. I am very tempted to deprecate it very soon.

For instance, the following file in your project root:

**.babelrc**
```json
{
  "presets": [ "meteor", "stage-0" ],
  "plugins": [ "transform-decorators-legacy" ]
}
```

... combined with the following Npm installs:

```bash
meteor npm install --save-dev babel-preset-meteor
meteor npm install --save-dev stage-0
meteor npm install --save-dev transform-decorators-legacy
```

... and the following meteor commands:

```bash
meteor add ecmascript
meteor add modules
meteor remove pbastowski:angular-babel
```

... will allow you to remove my `pbastowski:angular-babel` package from your project, if you don't rely on `ng-annotate`, that is. I haven't relied on ng-annotate for a long time now, especially so since I've been using my `angular2-now` library with AngularJS.

Any takers? I am very tempted to deprecate my angular-babel package soon. Let me know if the above works for you.

**Comment by Tallyb** [comment] 2016-05-30 19:00
Any chance to keep only ng-annotate separately? Sadly, we still heavily rely on it.

**Comment by kamilkisiela** [comment] 2016-05-30 19:09
@Tallyb I think I'm going to work on ng-annotate as a babel plugin in next few days.

**Comment by pbastowski** [comment] 2016-05-30 19:20
@Tallyb Unfortunately it is not possible to have both the `ecmascript` package and `ng-annotate` together, because Meteor only allows one compiler plugin per file extension, in this case `.js`. Once `ecmascript` has registered itself as the plugin for `.js` files no other plugin can, without causing an error. This is why I created the `pbastowski:angular-babel` package in the first place.

**Comment by pbastowski** [comment] 2016-05-30 19:22
@kamilkisiela 
Looks like someone already did this: https://www.npmjs.com/package/babel-plugin-ng-annotate

**Comment by kamilkisiela** [comment] 2016-05-30 19:24
@pbastowski Yes, but if I understand correctly it only works with @Inject decorator.

I was thinking about making it as easy as possible, so it would work out of the box and there won't be any issue with switching from your's angular-babel package to this babel plugin.

**Comment by pbastowski** [comment] 2016-05-30 19:27
@kamilkisiela Indeed, you're right.

So, about a year ago I had a thought about creating a Meteor compiler plugin package that would register itself against a specific file extension and then allow us to use other Meteor packages, in whichever order we wanted. But, then I created my package and gave up on the idea :)

I think your idea of a Babel extension is better indeed.

**Comment by pbastowski** [comment] 2016-05-30 19:30
@kamilkisiela 
Here is another babel ng-annotate plugin I found: https://www.npmjs.com/package/babel-plugin-angularjs-annotate

**Comment by kamilkisiela** [comment] 2016-05-30 19:37
@pbastowski It is much better than that plugin with @Inject decorator but this one has hard-coded `ng-annotate` package. I was thinking about using `ng-annotate` as one of dependency so it will be easier to maintain and to update if necessary.

It would soo nice if Meteor compiler plugin would support multiple compilers with priority settings, just like webpack does.

**Comment by pbastowski** [comment] 2016-05-30 21:13
It appears that the `ecmascript` package (with the `.babelrc` additions) is not producing useable sourcemaps for me. In my Chrome dev console, instead of seeing `app.js` I see `install.js`.

Anyone else having this issue with Meteor 1.3.3-beta.1 and `.babelrc` configured as I described above?

**Comment by JohnBernardsson** [comment] 2016-06-11 18:52
Hi, I am still with Meteor 1.3.2.4. These are my observations for source maps in are totally messed up in the following ways: 
**Chrome**: When you click on a source file (inside "app" folder with laptop symbol), a different source file appears there. 
**Firefox**: Here the source files seem to be correct, however when I set up a breakpoint, the browser never stops there.
**Edge**: I don't see here the sourcemaps, but an app.js file with everything concatenated. Here I can add breakpoints, and they work.

That's all! Pretty messed up for me, lol!

**Comment by mxab** [comment] 2016-06-19 07:37
@pbastowski I tried it but I need the ng-annotate feature unfortunately the `babel-plugin-angularjs-annotate` does not seem to work for me.
meteor complains about some es6 keywords in strict mode inside of the annotate plugin, I tried to transpile the code into es5 but then I get strange assertion errors during the process

**Comment by pbastowski** [comment] 2016-06-20 06:04
I'm using my angular-babel package and see no problems with source maps. However, my ng1 code does not actually rely on ng-annotate (because I use angular2-now), so, perhaps it's something to do with that. 

What I'm thinking is that ng-annotate may be adding extra lines of code, which then push the line index off by one line. See flow, below

Your code 
--> ng-annotate 
code with possible extra line(s) 
--> Babel 
code with source map accurate for ng-annotated code, but not your original code. 

Something to test...

**Comment by mxab** [comment] 2016-07-26 00:29
any updates on this?

**Comment by pbastowski** [comment] 2016-07-26 05:18
@mxab Sorry, no. I have been away on vacation most of the past month. I will look into this again next week when I'm back.

**Comment by mxab** [comment] 2016-08-09 08:46
sorry for being annoying, did you had the chance to look into it @pbastowski ? :)

**Comment by pbastowski** [comment] 2016-08-09 22:00
Hi Max. Sorry for not being able to get back to you. I'm really busy with projects and can't find time to investigate this angular-babel package issue. 

For the past several months I have been using my typescript package instead. Not that it supports ng-annotate, but, just saying that I haven't been using Babel lately and haven't relied on ng-annotate for a year or so. 

Have you tried any of the Babel Ng-annotate plugins, which me and Kamil mentioned in one of the earlier posts in this issue?

**Comment by mxab** [comment] 2016-08-09 23:06
Yep I tried the package you mentioned (https://github.com/Urigo/angular-meteor/issues/1327#issuecomment-226984077) and I think followed the steps how you described it.

I can try it again and see if anything changed.

Do you use the typescript package on an angular1 or angular2 application, does it work with the ecmascript package or is it an isolated package?

**Comment by pbastowski** [comment] 2016-08-20 08:24
My TypeScript package works along side with the ecmascript package and I use it for both Angular 1 and 2 projects.

However, my TypeScript package can also be used to completely replace Babel and by extension the ecmascript package, which is how I use it at the moment. I can configure it to also transpile both `.ts. and `.js` files. Please note that this is not the same functionality as the TypeScript `allowJs` flag, which simply imports JS code without transpiling.

**Comment by Urigo** [comment] 2016-10-16 10:11
@mxab what's the current status of this?

**Comment by mxab** [comment] 2016-10-17 09:22
@Urigo the issue still exists, currently I disabled js sourcemaps and debugging in the generated app.js

**Comment by Urigo** [comment] 2017-10-31 12:20
closing due to inactivity and cleanup after tons of new updates in the recent month.
Feel free to open a new issue if you are still affected

**Closed by Urigo** 2017-10-31 12:20 UTC
